var bachelorMajors = [{code:100,title:"Agriculture"},
{code:101,title:"Agricultural Business and Management"},
{code:102,title:"Agronomy and Crop Science"},
{code:103,title:"Animal Sciences"},
{code:104,title:"Horticulture and Business Services"},
{code:105,title:"Equestrian and Equine Studies"},
{code:107,title:"Food Science and Technology"},
{code:108,title:"Soil Sciences"},
{code:109,title:"Agroecology and Sustainable Agriculture"},
{code:120,title:"Architecture and Related Services"},
{code:121,title:"Architecture"},
{code:122,title:"Architectural Technology"},
{code:123,title:"City, Urban, Community and Regional Planning"},
{code:124,title:"Environmental Design"},
{code:125,title:"Landscape Architecture"},
{code:140,title:"Area, Ethnic, Cultural, Gender and Group Studies"},
{code:141,title:"Area Studies"},
{code:142,title:"Ethnic, Cultural Minority, Gender and Group Studies"},
{code:160,title:"Biological and Biomedical Sciences"},
{code:161,title:"Biology and Biological Sciences"},
{code:162,title:"Biochemistry"},
{code:163,title:"Biophysics"},
{code:164,title:"Biotechnology"},
{code:165,title:"Botany and Plant Biology"},
{code:166,title:"Cellular Biology and Anatomical Sciences"},
{code:167,title:"Ecology"},
{code:168,title:"Genetics"},
{code:169,title:"Marine Biology and Biological Oceanography"},
{code:170,title:"Microbiological Sciences and Immunology"},
{code:171,title:"Molecular Biology"},
{code:172,title:"Pharmacology and Toxicology"},
{code:173,title:"Physiology, Pathology and Related Sciences"},
{code:174,title:"Radiation Biology and Radiobiology"},
{code:175,title:"Zoology and Animal Biology"},
{code:185,title:"Neuroscience"},
{code:200,title:"Business Management, Marketing and Related Support Services"},
{code:201,title:"Accounting and Related Services"},
{code:202,title:"Actuarial Science"},
{code:203,title:"Administrative Assistant and Secretarial Science"},
{code:204,title:"Business Administration, Management and Operations"},
{code:205,title:"Business and Managerial Economics"},
{code:206,title:"Business Statistics"},
{code:207,title:"Construction Management"},
{code:208,title:"Fashion Merchandising"},
{code:209,title:"Finance and Financial Management Services"},
{code:210,title:"Sales, Merchandising and Related Marketing Operations"},
{code:211,title:"Hospitality Administration and Management"},
{code:212,title:"Human Resources Management and Services"},
{code:213,title:"Insurance"},
{code:214,title:"International Business"},
{code:215,title:"Investments and Securities"},
{code:216,title:"Labor and Industrial Relations"},
{code:217,title:"Management Information Systems and Services"},
{code:218,title:"Marketing and Marketing Management"},
{code:219,title:"Real Estate"},
{code:220,title:"Transportation and Mobility Management"},
{code:225,title:"Hotel, Motel and Restaurant Management"},
{code:230,title:"Meeting and Event Planning"},
{code:235,title:"Project Management"},
{code:250,title:"Communication, Journalism and Related Programs"},
{code:252,title:"Communication and Media Studies"},
{code:253,title:"Digital Communication and Multimedia"},
{code:254,title:"Journalism"},
{code:255,title:"Photojournalism"},
{code:257,title:"Radio and Television"},
{code:270,title:"Public Relations, Advertising and Applied Communication"},
{code:300,title:"Computer and Information Sciences and Support Services"},
{code:301,title:"Artificial Intelligence"},
{code:302,title:"Computer Programming"},
{code:303,title:"Computer Science"},
{code:304,title:"Computer Software and Media Applications"},
{code:305,title:"Computer Systems Analysis"},
{code:306,title:"Computer Systems Networking and Telecommunications"},
{code:307,title:"Data Processing"},
{code:308,title:"Information Sciences and Studies"},
{code:309,title:"Information Technology Project Management"},
{code:310,title:"Modeling, Virtual Environments and Simulation"},
{code:360,title:"Military Technologies and Applied Sciences"},
{code:390,title:"Construction Trades"},
{code:391,title:"Carpentry"},
{code:400,title:"Education"},
{code:401,title:"Adult and Continuing Education Teaching"},
{code:402,title:"Agricultural Teacher Education"},
{code:403,title:"Art Teacher Education"},
{code:404,title:"Bilingual, Multilingual and Multicultural Education"},
{code:405,title:"Business Teacher Education"},
{code:407,title:"Early Childhood Education and Teaching"},
{code:408,title:"Educational Administration and Supervision"},
{code:416,title:"Education and Teaching of Gifted and Talented"},
{code:417,title:"Elementary Education and Teaching"},
{code:418,title:"English and Language Arts Teacher Education"},
{code:419,title:"Family, Consumer Sciences and Home Economics Teacher Education"},
{code:420,title:"Health Teacher Education"},
{code:421,title:"Higher Education and Administration"},
{code:422,title:"Junior High, Intermediate and Middle School Teacher Education"},
{code:423,title:"Kindergarten, Preschool Teacher Education"},
{code:424,title:"Mathematics Teacher Education"},
{code:425,title:"Music Teacher Education"},
{code:426,title:"Coaching and Physical Education Teaching"},
{code:427,title:"Psychology Teacher Education"},
{code:429,title:"Science Teacher Education"},
{code:430,title:"Secondary Education Teaching"},
{code:431,title:"Social Science Teacher Education"},
{code:432,title:"Special Education Teaching"},
{code:433,title:"Student Counseling and Personnel Services"},
{code:434,title:"Teaching ESL and ESL Language Instructor"},
{code:435,title:"Technology and Industrial ArtsTeacher Education"},
{code:450,title:"Engineering"},
{code:451,title:"Aerospace, Aeronautical and Space Engineering"},
{code:452,title:"Agricultural Engineering"},
{code:453,title:"Architectural Engineering"},
{code:454,title:"Bioengineering and Biomedical Engineering"},
{code:455,title:"Chemical Engineering"},
{code:456,title:"Civil Engineering"},
{code:457,title:"Computer Engineering"},
{code:458,title:"Construction Engineering"},
{code:459,title:"Electrical and Electronics Engineering"},
{code:460,title:"Engineering Mechanics"},
{code:461,title:"Engineering and Applied Physics"},
{code:462,title:"Engineering Science"},
{code:463,title:"Environmental and Health Engineering"},
{code:464,title:"Geological and Geophysical Engineering"},
{code:465,title:"Industrial Engineering"},
{code:466,title:"Materials Engineering"},
{code:467,title:"Mechanical Engineering"},
{code:468,title:"Mining and Mineral Engineering"},
{code:469,title:"Naval Architecture and Marine Engineering"},
{code:470,title:"Nuclear Engineering"},
{code:471,title:"Ocean Engineering"},
{code:472,title:"Petroleum Engineering"},
{code:473,title:"Surveying Engineering"},
{code:475,title:"Polymer and Plastics Engineering"},
{code:478,title:"Biochemical Engineering"},
{code:480,title:"Biological and Biosystems Engineering"},
{code:485,title:"Engineering Chemistry"},
{code:490,title:"Pre-Engineering"},
{code:500,title:"Engineering Technologies"},
{code:501,title:"Computer Engineering Technology"},
{code:502,title:"Drafting and Design Engineering Technology"},
{code:507,title:"Nuclear Engineering Technology"},
{code:508,title:"Plastics and Polymer Engineering Technology"},
{code:509,title:"Telecommunications Technology"},
{code:510,title:"Civil Engineering Technology"},
{code:511,title:"Electrical Engineering Technology"},
{code:512,title:"Environmental Control Technology"},
{code:513,title:"Industrial Production Technology"},
{code:514,title:"Mechanical Engineering Technology"},
{code:515,title:"Nanotechnology"},
{code:516,title:"Robotics Technology"},
{code:520,title:"English Language and Literature and  Letters"},
{code:521,title:"American Literature of United States and Canada"},
{code:522,title:"Creative Writing"},
{code:523,title:"English Literature of British and Commonwealth"},
{code:525,title:"Professional, Technical, Business and Scientific Writing"},
{code:535,title:"Rhetoric and Composition and Writing Studies"},
{code:540,title:"Family and Consumer Sciences and Human Sciences"},
{code:541,title:"Apparel and Textiles"},
{code:542,title:"Foods, Nutrition and Wellness Studies"},
{code:543,title:"Housing and Human Environments"},
{code:544,title:"Human Development and Family Studies"},
{code:550,title:"Foreign Languages, Literatures and Linguistics"},
{code:551,title:"African Languages, Literatures and Linguistics"},
{code:552,title:"Arabic Language and Literature"},
{code:553,title:"Classics and Classical Languages, Literatures and Linguistics"},
{code:554,title:"Comparative Literature"},
{code:555,title:"East Asian Languages, Literatures and Linguistics"},
{code:556,title:"French Language and Literature"},
{code:557,title:"German Language and Literature"},
{code:558,title:"Italian Language and Literature"},
{code:559,title:"Linguistics"},
{code:560,title:"Russian Language and Literature"},
{code:561,title:"Spanish Language and Literature"},
{code:600,title:"Health Professions and Related Programs"},
{code:601,title:"Allied Health and Medical Assisting Services"},
{code:602,title:"Allied Health Diagnostic, Intervention and Treatment"},
{code:603,title:"Athletic Training and Trainer"},
{code:605,title:"Clinical and Medical Laboratory Science and Research"},
{code:606,title:"Communication Sciences and Disorders"},
{code:607,title:"Dental Hygiene and Hygienist"},
{code:608,title:"Dental Laboratory Technology and Technician"},
{code:609,title:"Dental Support Services and Allied Professions"},
{code:610,title:"Dietetics and Clinical Nutrition Services"},
{code:611,title:"Environmental Health"},
{code:612,title:"Health and Medical Administrative Services"},
{code:613,title:"Health Services and Allied Health and Health Sciences"},
{code:614,title:"Hospital and Health Care Facilities Administration"},
{code:615,title:"Mental and Social Health Services"},
{code:616,title:"Music Therapy and Therapist"},
{code:617,title:"Nuclear Medical Technology and Technologist"},
{code:618,title:"Nurse Anesthetist"},
{code:619,title:"Nursing"},
{code:622,title:"Osteopathic Medicine and Osteopathy"},
{code:625,title:"Physician Assistant"},
{code:626,title:"Podiatric Medicine and Podiatry"},
{code:627,title:"Predentistry Studies"},
{code:628,title:"Pre-Medicine and Pre-Medical Studies"},
{code:629,title:"Prepharmacy Studies"},
{code:630,title:"Preveterinary Studies"},
{code:631,title:"Public Health"},
{code:632,title:"Radiologic Technology and Science and Radiographer"},
{code:633,title:"Rehabilitation and Therapeutic Professions"},
{code:634,title:"Respiratory Care Therapy and Therapist"},
{code:636,title:"Surgical Technology and Technologist"},
{code:637,title:"Therapeutic Recreation and Recreational Therapy"},
{code:640,title:"Alternative and Complementary Medicine and Systems"},
{code:650,title:"Health and Wellness"},
{code:670,title:"Pharmaceutical Marketing and Management"},
{code:671,title:"Pharmaceutical Sciences"},
{code:675,title:"Prechiropractic Studies"},
{code:678,title:"Preoccupational Therapy Studies"},
{code:680,title:"Preoptometry Studies"},
{code:682,title:"Prephysical Therapy Studies"},
{code:700,title:"History"},
{code:701,title:"American History"},
{code:702,title:"European History"},
{code:710,title:"Legal Professions and Studies"},
{code:711,title:"Legal Assistant and Paralegal"},
{code:712,title:"Prelaw Studies"},
{code:720,title:"Liberal Arts and Sciences, General Studies and Humanities"},
{code:721,title:"General Studies"},
{code:722,title:"Humanities and Humanistic Studies"},
{code:723,title:"Liberal Arts and Sciences"},
{code:730,title:"Library Science and Administration"},
{code:731,title:"Library and Archives Assisting"},
{code:740,title:"Mathematics and Statistics"},
{code:741,title:"Applied Mathematics"},
{code:742,title:"Mathematics"},
{code:743,title:"Statistics"},
{code:746,title:"Financial Mathematics"},
{code:750,title:"Mechanic and Repair Technologies and  Technician"},
{code:751,title:"Airframe Mechanics and Aircraft Maintenance Technology"},
{code:752,title:"Automobile and Automotive Mechanics Technology"},
{code:753,title:"Electrical and Electronics Maintenance and Repair Technology"},
{code:754,title:"HVAC Maintenance Technology"},
{code:770,title:"Multi and Interdisciplinary Studies"},
{code:771,title:"Biological and Physical Sciences"},
{code:772,title:"International and Global Studies"},
{code:773,title:"Mathematics and Computer Science"},
{code:775,title:"Nutrition Sciences"},
{code:780,title:"Human Biology"},
{code:784,title:"Marine Sciences"},
{code:787,title:"Sustainability Studies"},
{code:790,title:"Natural Resources and Conservation"},
{code:791,title:"Environmental Science"},
{code:792,title:"Environmental Studies"},
{code:793,title:"Fishing and Fisheries Sciences and Management"},
{code:794,title:"Forestry"},
{code:795,title:"Natural Resources Management and Policy"},
{code:796,title:"Wildlife, Fish, Wildlands Science and Management"},
{code:800,title:"Parks, Recreation, Leisure and Fitness Studies"},
{code:801,title:"Health and Physical Education and Fitness"},
{code:802,title:"Parks and Recreation Facilities Management"},
{code:803,title:"Sport and Fitness Administration and  Management"},
{code:804,title:"Outdoor Education"},
{code:805,title:"Sports Studies"},
{code:810,title:"Personal and Culinary Services"},
{code:811,title:"Cosmetology and Personal Grooming Services"},
{code:812,title:"Funeral Service and Mortuary Science"},
{code:815,title:"Culinary Arts"},
{code:820,title:"Philosophy and Religious Studies"},
{code:821,title:"Philosophy"},
{code:822,title:"Religion and Religious Studies"},
{code:830,title:"Physical Sciences"},
{code:831,title:"Analytical Chemistry"},
{code:832,title:"Astronomy"},
{code:833,title:"Astrophysics"},
{code:834,title:"Atmospheric Sciences and Meteorology"},
{code:835,title:"Atomic and Molecular Physics"},
{code:836,title:"Chemistry"},
{code:837,title:"Geological and Earth Sciences and Geosciences"},
{code:838,title:"Nuclear Physics"},
{code:839,title:"Oceanography, Chemical and Physical"},
{code:840,title:"Organic Chemistry"},
{code:841,title:"Paleontology"},
{code:842,title:"Physical Chemistry"},
{code:843,title:"Physics"},
{code:844,title:"Planetary Astronomy and Science"},
{code:850,title:"Forensic Chemistry"},
{code:854,title:"Materials Science"},
{code:860,title:"Precision Production"},
{code:861,title:"Machine Tool Technology and Machinist"},
{code:862,title:"Precision Metal Working"},
{code:870,title:"Psychology"},
{code:871,title:"Clinical Psychology"},
{code:872,title:"Developmental and Child Psychology"},
{code:873,title:"Experimental Psychology"},
{code:874,title:"Industrial and Organizational Psychology"},
{code:875,title:"Social Psychology"},
{code:880,title:"Public Administration and Social Services"},
{code:881,title:"Human Services"},
{code:882,title:"Public Administration"},
{code:883,title:"Public Policy Analysis"},
{code:884,title:"Social Work"},
{code:890,title:"Homeland Security, Law Enforcement, Firefighting and Related Protective Services"},
{code:891,title:"Criminal Justice and Corrections"},
{code:892,title:"Criminal Justice and Law Enforcement Administration"},
{code:893,title:"Fire Protection"},
{code:894,title:"Forensic Science and Technology"},
{code:895,title:"Cyber and Computer Forensics and Counterterrorism"},
{code:896,title:"Financial Forensics and Fraud Investigation"},
{code:897,title:"Homeland Security"},
{code:900,title:"Social Sciences"},
{code:901,title:"Anthropology"},
{code:902,title:"Archaeology"},
{code:903,title:"Criminology"},
{code:904,title:"Economics"},
{code:905,title:"Geography"},
{code:906,title:"International Relations and Affairs"},
{code:907,title:"Political Science and Government"},
{code:908,title:"Sociology"},
{code:920,title:"Theology and Religious Vocations"},
{code:921,title:"Religious Education"},
{code:922,title:"Theological and Ministerial Studies"},
{code:930,title:"Transportation and Materials Moving"},
{code:931,title:"Airline Flight Attendant"},
{code:932,title:"Air Traffic Controller"},
{code:940,title:"Visual and Performing Arts"},
{code:941,title:"Art History, Criticism and Conservation"},
{code:942,title:"Dance"},
{code:943,title:"Drama and Theater Arts"},
{code:944,title:"Design and Applied Arts"},
{code:945,title:"Fashion and Apparel Design"},
{code:946,title:"Film and Video and Photographic Arts"},
{code:947,title:"Fine and Studio Art"},
{code:948,title:"Graphic Design"},
{code:949,title:"Interior Design"},
{code:950,title:"Music"},
{code:951,title:"Music History, Literature and Theory"},
{code:952,title:"Music Performance"},
{code:953,title:"Music Theory and Composition"},
{code:954,title:"Photography"},
{code:955,title:"Technical Theater and Theater Design and Technology"},
{code:956,title:"Voice and Operation"},
{code:960,title:"Arts, Entertainment and Media Management"},
{code:965,title:"Digital Arts"},
{code:970,title:"Game and Interactive Media Design"},
{code:975,title:"Music Technology"},
{code:976,title:"Musical Theater"},
{code:990,title:"Other"},
{code:999,title:"Undecided"}];
