var udemyprofessions = [
{"id": "3-D Animator","tags":["3D Modeling","3DS Max","Acrobat","Adobe","Animation","Apps","Art","AutoCAD","Construction","Course Development","Content Development","Design","Digital Content"]},
{"id": "3-D Object Modeler","tags":["3D Modeling","3DS Max","Acrobat","Adobe","Animation","Apps","Art","AutoCAD","Construction","Course Development","Content Development","Design","Digital Content"]},
{"id": "Actor","tags":["Athletics","Casting","Cinema","Diet","Entertainment","Fashion","Film","Fitness","Makeup","Physical Improvements","Public Speaking","Relationships","Self Confidence"]},
{"id": "Animator","tags":["3D Modeling","3DS Max","Acrobat","Adobe","Animation","Apps","Art","AutoCAD","Construction","Course Development","Content Development","Design","Digital Content"]},
{"id": "Architect","tags":["3D Modeling","3DS Max","Acrobat","Adobe","Art","AutoCAD","Construction","Design","Digital Content","Digital Design","Image Editing","Photoshop","Architecture"]},
{"id": "Art Director","tags":["3D Modeling","3DS Max","Acrobat","Adobe","Animation","Apps","Art","AutoCAD","Course Development","Content Development","Design","Digital Content","Digital Design"]},
{"id": "Artist/Illustrator","tags":["3D Modeling","3DS Max","Acrobat","Adobe","Animation","Apps","Art","AutoCAD","Construction","Course Development","Content Development","Design","Digital Content"]},
{"id": "Assistant Designer","tags":["3D Modeling","3DS Max","Acrobat","Adobe","Animation","Apps","Art","AutoCAD","Course Development","Content Development","Design","Digital Content","Digital Design"]},
{"id": "Audio Film Editor","tags":["Audio Editing","Audio Production","Digital Content","Entertainment","Film","IMovie","Premiere Elements 11","Premiere Pro","Premiere Pro CS5","Premiere Pro CS6","Pro Tools 10","Cut Pro","Cinema"]},
{"id": "Audio/Sound Engineer","tags":["Audio Editing","Audio Production","Entertainment","Film","IMovie","Communications","Management","Mac"]},
{"id": "Autocad Technician","tags":["3D Modeling","3DS Max","Acrobat","Adobe","Animation","Art","AutoCAD","Construction","Design","Digital Content","Digital Design","Dreamweaver","Image Editing"]},
{"id": "Automotive Designer","tags":["3D Modeling","3DS Max","Acrobat","Adobe","Animation","Art","AutoCAD","Design","Digital Content","Digital Design","Fashion","Image Editing","Illustrator"]},
{"id": "Broadcaster","tags":["Communications","Energy","Entertainment","Film","Public Speaking","Self Confidence","Speech","Interview","Relationships","Networking","Psychology"]},
{"id": "Cad Design Engineer","tags":["3D Modeling","3DS Max","Acrobat","Adobe","Animation","Art","Architecture","AutoCAD","Construction","Design","Digital Design","Dreamweaver","Image Editing"]},
{"id": "Choreographer","tags":["Art","Athletics","Casting","Cinema","Communications","Energy","Entertainment","Fashion","Film","Fitness","Physical Improvements","Pilates","Public Speaking"]},
{"id": "Cinematographer","tags":["Art","Audio Production","Camtasia","Cinema","Communications","Decorating","Design","DSLR","Entertainment","Fashion","Film","HDR","Photography"]},
{"id": "Civil Engineer","tags":["3D Modeling","3DS Max","Acrobat","Adobe","AutoCAD","Construction","Design","Architecture","Industrial","Negotiating","Photography","Physics"]},
{"id": "Commercial Artist","tags":["Art","Branding","Camtasia","Content Development","Design","Digital Content","Digital Design","Image Editing","Photography","Photoshop","Product Development","Publishing","Snapseed"]},
{"id": "Computer Graphics Spec.","tags":["3D Modeling","3DS Max","Acrobat","Adobe","Architecture","Art","Content Development","CS4","CS5","CS6","CSS","Design","Digital Content"]},
{"id": "Dancer","tags":["Art","Athletics","Casting","Cinema","Communications","Energy","Entertainment","Fashion","Film","Fitness","Makeup","Physical Improvements","Pilates"]},
{"id": "Decorator","tags":["Design","Decorating","Art","Photography","B2B","Communications","Business"]},
{"id": "Designer","tags":["3D Modeling","3DS Max","Acrobat","Adobe","Art","AutoCAD","Design","Digital Content","Digital Design","Dreamweaver","Fashion","Image Editing","Illustrator"]},
{"id": "Desktop Publisher","tags":["3D Modeling","3DS Max","Acrobat","Adobe","Art","AutoCAD","Computing","CS4","CS5","CS6","CSS","Design","Digital Content"]},
{"id": "Digital Artist","tags":["3D Modeling","3DS Max","Acrobat","Adobe","Animation","Apps","Art","AutoCAD","Course Development","Content Development","Design","Digital Content","Digital Design"]},
{"id": "Digital Media Specialist","tags":["Acrobat","Adobe","Content Development","Content Management","CS4","CS5","CS6","CSS","Cut Pro","Digital Content","Digital Design","Entertainment","Illustrator"]},
{"id": "Digital Video/Sound Editor","tags":["Audio Editing","Audio Production","Content Development","Content Management","Digital Content","Digital Design","Entertainment","Film","IMovie","Premiere Elements 11","Premiere Pro","Premiere Pro CS5","Premiere Pro CS6"]},
{"id": "Fashion Designer","tags":["3D Modeling","3DS Max","Athletics","Branding","Cinema","CS4","CS5","CS6","CSS","Decorating","Design","Entertainment","Fashion"]},
{"id": "Fashion Events Mgr.","tags":["Cinema","Decorating","Design","Entertainment","Fashion","Film","International","Makeup","Photoshop","Project","Self Confidence","TV Appearance","Wedding"]},
{"id": "Fashion Merchandiser","tags":["Art","Design","Entertainment","Fashion","International","Makeup","Photoshop","Project","Communications","B2B","Negotiating","Marketing","QuickBooks"]},
{"id": "Film Producer","tags":["Audio Editing","Audio Production","Camtasia","Casting","Cinema","Entertainment","Fashion","Film","Management","Photography","Premiere Elements 11","Premiere Pro","Premiere Pro CS5"]},
{"id": "Film Producer Asst.","tags":["Audio Editing","Audio Production","Camtasia","Casting","Cinema","Entertainment","Fashion","Film","Management","Photography","Premiere Elements 11","Premiere Pro","Premiere Pro CS5"]},
{"id": "Floral Designer","tags":["Art","Design","Wedding","Decorating"]},
{"id": "Game Designer","tags":["3D Modeling","3DS Max","Acrobat","Adobe","Animation","Apps","Art","AutoCad","Content Development","Design","Digital Content","Digital Design","Dreamweaver"]},
{"id": "Glamour Photographer","tags":["CS4","CS5","CS6","CSS","Design","Digital Content","Digital Design","Illustrator","Image Editing","Photo Restoration","Photoshop","Photography","Publishing"]},
{"id": "Graphic Designer","tags":["3D Modeling","3DS Max","Acrobat","Adobe","Art","CS4","CS5","CS6","CSS","Cut Pro","Design","Digital Content","Digital Design"]},
{"id": "Industrial Designer","tags":["3D Modeling","3DS Max","Acrobat","Adobe","Animation","AutoCAD","Construction","Design","Digital Design","Image Editing","Illustrator","Photoshop","Physics"]},
{"id": "Industrial Engineer","tags":["3D Modeling","3DS Max","Acrobat","Adobe","Animation","AutoCAD","Construction","Design","Digital Design","Image Editing","Illustrator","Photoshop","Physics"]},
{"id": "Interior Designer","tags":["Art","AutoCAD","Design","Fashion","Illustrator","Photoshop","Communications","Wedding","Decorating","B2B","Communications"]},
{"id": "Jeweler","tags":["3D Modeling","3DS Max","Art","AutoCAD","Branding","Business","Design","Fashion","Negotiating","Networking","Sales"]},
{"id": "Journalist","tags":["Blog","Communications","Content Development","Content Management","Education","Entertainment","Fashion","Film","International","Legal","List Building","Management","Networking"]},
{"id": "Landscape Architect","tags":["3D Modeling","3DS Max","Acrobat","Adobe","Art","AutoCAD","Construction","Design","Digital Content","Digital Design","Image Editing","Photoshop","Architecture"]},
{"id": "Media Buyer","tags":["Affiliate","Analysis","B2B","Business","Communications","Content Management","Digital Content","Email","Entertainment","Google","LinkedIn","List Building","Management"]},
{"id": "Motion Picture Director","tags":["Art","Audio Editing","Audio Production","Branding","Camtasia","Casting","Cinema","Content Development","Cut Pro","CS4","CS5","CS6","CSS"]},
{"id": "Musician","tags":["Art","Audio Editing","Audio Production","Cinema","Entertainment","Film","Networking","Physical Improvements","Public Speaking","Publishing","Speech","YouTube","GarageBand"]},
{"id": "Photographer","tags":["CS4","CS5","CS6","CSS","Design","Digital Content","Digital Design","Illustrator","Image Editing","Photo Restoration","Photoshop","Photography","Publishing"]},
{"id": "Producer","tags":["Art","Audio Editing","Audio Production","Branding","Camtasia","Casting","Cinema","Content Development","Cut Pro","CS4","CS5","CS6","CSS"]},
{"id": "Publisher","tags":["Acrobat","Adobe","Art","Content Development","Content Management","CS4","CS5","CS6","CSS","Design","Digital Content","Digital Design","Illustrator"]},
{"id": "Radio/TV Announcer","tags":["Communications","Energy","Entertainment","Public Speaking","Self Confidence","Speech","Technology","TV Appearance","Content Development","Content Management"]},
{"id": "Singer","tags":["Audio Editing","Audio Production","Cinema","Energy","Entertainment","Networking","Physical Improvements","Public Speaking","Publishing","Speech","YouTube","GarageBand","Fund Raising"]},
{"id": "Technical Illustrator","tags":["3D Modeling","3DS Max","Acrobat","Adobe","AutoCAD","Design","Digital Design","Image Editing","Illustrator","Photoshop","Physics","Cut Pro","CS4"]},
{"id": "Theatrical Director","tags":["Content Development","Design","Fashion","Video Content","Video Editing","Video Production","Communications","Decorating","Writing","Word","Negotiating"]},
{"id": "TV Programmer","tags":["Business","Cinema","Communications","Digital Content","Entertainment","Film","International","Legal","Management","Marketing","Time management","TV Appearance","Video Content"]},
{"id": "Urban Planner","tags":["3D Modeling","3DS Max","Acrobat","Adobe","Art","AutoCAD","Construction","Design","Digital Design","Image Editing","Photoshop","Architecture","Business"]},
{"id": "Web Designer","tags":["3D Modeling","3DS Max","Acrobat","Adobe","Animation","Android","Art","Chrome","Cloud Computing","Computing","Content Development","Content Management","Copywriting"]},
{"id": "Aerospace Engineer","tags":["3D Modeling","3DS Max","Analysis","Architecture","AutoCAD","Communications","Computing","Construction","Design","Hardware","Industrial","Management","Physics"]},
{"id": "Air Traffic Controller","tags":["Analysis","Communications","Computing","Management","Time management","Speech"]},
{"id": "Aircraft Maintenance Technician","tags":["Technology","Time management","Physics"]},
{"id": "Airframe & Powerplant Technician","tags":["Athletics","Physical improvements","Forklift","Physics","Project","Technology","Time management","Fitness","Energy"]},
{"id": "Flight Attendant","tags":["Communications","Energy","Physical Improvements","Public Speaking","Self Confidence","Speech","Psychology"]},
{"id": "Flight Engineer","tags":[""]},
{"id": "Pilot","tags":["Communications","Energy","Physical Improvements","Physics","Self Confidence","Speech","Technology","Time management","Pilot"]},
{"id": "Barber","tags":["Fashion","Makeup","Networking","Physical Improvements","Fitness"]},
{"id": "Cosmetologist","tags":["Makeup","Physical Improvement","Fashion"]},
{"id": "Hair Stylist","tags":["Cinema","Entertainment","Fashion","Film","Makeup","Networking","Physical Improvements","Fitness","Wedding","Fashion"]},
{"id": "Manicurist","tags":["Networking","Physical Improvements"]},
{"id": "Skin Care Consultant","tags":["Networking","Physical Improvements","Healing","Makeup","Fashion","Nutrition"]},
{"id": "Accountant/CPA","tags":["Accounting","Analysis","Business","Computing","Ecommerce","Finance","Investing","Management","Networking","Office","Outlook","Project","QuickBooks"]},
{"id": "Acquisition Analyst","tags":["Analysis","Accounting","Branding","Communications","Excel","Finance","Interview","Investing","Market Research","Modeling","Negotiating","Office","Power Point"]},
{"id": "Administrative Analyst","tags":["Accounting","Analysis","Business","Computing","Crystal Reports","Excel","Investing","Management","Market Research","Office","QuickBooks","Reporting"]},
{"id": "Advertising Manager","tags":["Branding","Business","Communications","Computing","Content Development","Content Management","Design","Digital Content","Digital Design","Entertainment","Facebook","Management","Market Research"]},
{"id": "Auditor","tags":["Accounting","Analysis","Business","Computing","Finance","Investing","Legal","Management","Networking","Office","Outlook","Project","QuickBooks"]},
{"id": "Banker","tags":["Math","Business","Technical Analysis","Modeling","Market Research","Accounting","Finance","Investing","Networking","Communications","Negotiating","FX"]},
{"id": "Bookkeeping Clerk","tags":["Analysis","Business","Computing","Networking","Office","Outlook","Project","QuickBooks","Reporting","Technology","Time management","Accounting","QuickBooks"]},
{"id": "Business Analyst","tags":["Analysis","Accounting","Branding","Communications","Excel","Finance","Interview","Investing","Market Research","Modeling","Negotiating","Office","Power Point"]},
{"id": "Business Planner","tags":["Product Development","Business","Finance","Communications","Market Research","Analysis","Reporting","Writing","Word","Excel","Power Point"]},
{"id": "Business Programmer","tags":["Ajax","BGP","C Language","C++","Cocoa","Computing","Dreamweaver","E4X","HTML","Java Swing","JavaScript","Mac","Networks"]},
{"id": "Buyer/Purch'g Agent","tags":["B2B","Negotiating","Networking","Communications","Sales"]},
{"id": "Cash Manager","tags":["Business","Accounting","Finance","Excel","Analysis","Investing"]},
{"id": "Collection Mgr.","tags":["Accounting","Analysis","Business","Computing","Crystal Reports","Excel","Finance","Legal","Management","Networking","Reporting","Technical Analysis","Communications"]},
{"id": "Compensation Analyst","tags":["Analysis","Accounting","Branding","Communications","Excel","Finance","Investing","Market Research","Modeling","Negotiating","Office","Power Point","Reporting"]},
{"id": "Comptroller","tags":["Accounting","Analysis","Business","Computing","Ecommerce","Finance","Investing","Management","Networking","Office","Outlook","Project","QuickBooks"]},
{"id": "Consumer Relations Mgr.","tags":["Sales","project","analysis","content development","communications","finance","market research","marketing","management","networking","Modeling"]},
{"id": "Contract Administrator","tags":["Accounting","Analysis","Business","Communications","Computing","Construction","Excel","Finance","Industrial","International","Legal","List Building","Management"]},
{"id": "Copywriter","tags":["Copywriting","Writing","Business","Outlook","WordPress","Marketing","Branding","Word"]},
{"id": "Corporate Planner","tags":["Analysis","Accounting","Branding","Communications","Excel","Finance","Interview","Investing","Market Research","Modeling","Negotiating","Office","Power Point"]},
{"id": "Credit/Loan Manager","tags":["Finance","Business","Analysis","Excel","Negotiating","Office","Management"]},
{"id": "Cruise Director","tags":["Communications","Time Management","Content Development","Management","Public Speaking","Entertainment","Casting"]},
{"id": "Cryptologist","tags":["Analysis","Computing","Data storage","Digital content","Email","Evernote","GIT","Online security","Programming","IPv4","Python","Qt framework","xcode"]},
{"id": "Database Admin (DBA)","tags":["Analysis","BGP","Business","Communications","Computing","Content Management","Data Storage","GIT","Hardware","Management","Networks","Office","Online"]},
{"id": "Diamond Merchant","tags":["Sales","Networking","B2B","Negotiating"]},
{"id": "Direct Marketer","tags":["Content Development","Content Management","Design","Digital Content","Digital Design","Entertainment","Illustrator","Networking","Negotiating","Marketing","Branding","LinkedIn","Facebook"]},
{"id": "Distribution Manager","tags":["Communication","Networking","Management","Time Management","Project","Negotiating","Business","Ecommerce","Relationships"]},
{"id": "Economist","tags":["Analysis","Market research","PR","Computing","Modeling","Investing","Finance","Business"]},
{"id": "Employment Agent","tags":["Analysis","Career Improvement","Communications","Computing","Excel","Management","Market Research","Networking","Recruitment"]},
{"id": "Entrepreneur","tags":["Analysis","Accounting","Branding","Communications","Excel","Finance","Interview","Investing","Market Research","Modeling","Negotiating","Office","Business"]},
{"id": "Escrow Officer","tags":["Communications","Time Management","Accounting"]},
{"id": "Executive Assistant","tags":["Accounting","Business","Computing","Excel","Office","Time management","Communications","QuickBooks","Word","Power Point"]},
{"id": "Executive Recruiter","tags":["Networking","Communications","Relationships","Recruitment","Legal"]},
{"id": "Financial Analyst","tags":["Math","Business","Technical Analysis","Modeling","Market Research","Accounting","Finance","Macros","Options"]},
{"id": "Financial Planner","tags":["Finance","Accounting","Excel","Modeling","Analysis","Business","Investing","International","Technical Analysis","Communications","Networking","Math"]},
{"id": "Financier","tags":["Investing","Technical Analysis","Market research","Modeling","Reporting","Math","Marketing","Accounting","Analysis","Networking"]},
{"id": "Forensic Accountant","tags":["Accounting","Analysis","Business","Computing","Finance","Office","Outlook","Project","QuickBooks","Reporting","Technology","Time management","Math"]},
{"id": "Franchise Management","tags":["Sales","Business","Finance","Communications","Market Research","Networking","Legal","List Building"]},
{"id": "Fund Raiser","tags":["Analysis","Branding","Business","Communications","Facebook","Fund Raising","List Building","Public Speaking","Relationships","Social Media","Telemarketing","Networking","Sales"]},
{"id": "Funeral Director","tags":["Management","Communications","Relationships","Psychology"]},
{"id": "General Manager","tags":["HR","Communications","Time Management","Management","Public Speaking","Business","Marketing","Finance","Accounting","Excel","Office","Project","Word"]},
{"id": "Golf Club Manager","tags":["Communications","Entertainment","Fund Raising","Management","Relationships","Computing","Office","Word","Power Point","Excel","Networking","Accounting","QuickBooks"]},
{"id": "Home Economist","tags":["Finance","Education","Communication","Investing","Market Research"]},
{"id": "Hotel Manager","tags":["HR","Communications","Time Management","Management","Public Speaking","Networking","Entertainment","Interview","Social Media","Business","Ecommerce","Marketing","QuickBooks"]},
{"id": "Human Resource Mgr.","tags":["Communications","Management","Recruitment","HR"]},
{"id": "Importer","tags":["Business","Networking","Management","Negotiating","Business","Ecommerce","Relationships","Communication","International","Fund Raising"]},
{"id": "Insurance Adjuster","tags":["Analysis","Accounting","Communications","Excel","Finance","Interview","Investing","Market Research","Modeling","Negotiating","Office","Power Point","Reporting"]},
{"id": "International Accountant","tags":["Accounting","Analysis","Business","Computing","Ecommerce","Finance","Investing","Management","Networking","Office","Outlook","Project","QuickBooks"]},
{"id": "Investment Banker","tags":["Math","Business","Technical Analysis","Modeling","Market Research","Accounting","Finance","investing","Networking","Communication","Negotiating"]},
{"id": "Investment Manager","tags":["Math","Business","Technical Analysis","Modeling","Market Research","Accounting","Finance","investing","Technical Analysis","Networking","Communication","Negotiating","FX"]},
{"id": "Labor Negotiator","tags":["Business","Networking","Recruitment","Negotiating","Relationships","Communication","Public Speaking","Finance"]},
{"id": "Labor Organizer","tags":["Business","Networking","Recruitment","Negotiating","Relationships","Communication","Public Speaking"]},
{"id": "Labor Relations Mgr.","tags":["Business","Negotiating","Relationships","Communication","Public Speaking","Math"]},
{"id": "Loan Officer","tags":["Finance","Business","Analysis","Excel","Office","Management","Technical Analysis","Communication","Math","Real Estate","Relationships","Investing"]},
{"id": "Management Consultant","tags":["Management","Time Management","Communication","Analysis","Business","Finance","Excel","Market Research","Power Point"]},
{"id": "Marketing Analyst","tags":["Analysis","Business","Marketing","Networking","Technology","Sales","Ecommerce","Broker"]},
{"id": "Marketing Manager","tags":["Market Research","Marketing","Analysis","Excel","Finance","Management","Office","Power Point","Business","Communications","Networking","LinkedIn","Affiliate"]},
{"id": "Materials Manager","tags":["Project","Analysis","Industrial","Management","Time Management","Communication","Relationships","Sales","Negotiating","Business","B2B"]},
{"id": "Medical Investor","tags":["Analysis","Business","Investing","Management","Market Research","Networking","Technical Analysis","Medicine","Finance","Legal"]},
{"id": "Medical Receptionist","tags":["Office","Excel","Communications","Management","Project","Time management","HR","List Building","Relationships"]},
{"id": "Merchandiser","tags":["Project","Analysis","Industrial","Management","Time Management","Communication","Relationships","Sales","Negotiating","Business","B2B"]},
{"id": "MIS Manager/Director","tags":["Management","Access","Analysis","Apps","Cloud computing","Computing","Data storage","Digital content","Email","Keynote","MAC","Macros","Mobile"]},
{"id": "New Product Specialist","tags":["Sales","Business","Communications","Time Management","Content Development","Management","Product Development","PowerPoint","Networking","Market Research","Modeling","Psychology","Social Media"]},
{"id": "Office Manager","tags":["HR","Communications","Time Management","Power Point","Excel","Office"]},
{"id": "Payroll Manager","tags":["Accounting","Analysis","Business","Computing","Data Storage","Finance","Management","Networking","Office","Outlook","Project","QuickBooks","Reporting"]},
{"id": "Personnel Specialist","tags":["Communications","Management","Recruitment","HR"]},
{"id": "Private Banker","tags":["Math","Business","Technical Analysis","Modeling","Market Research","Accounting","Finance","Investing","Networking","Communications","Negotiating","FX"]},
{"id": "Product Manager","tags":["Product Development","Business","Finance","Communications","Market Research","Analysis","Reporting","Writing","Word","Excel","Power Point"]},
{"id": "Production Planner","tags":["Product Development","Business","Finance","Communications","Market Research","Analysis","Reporting","Writing","Word","Excel","Power Point"]},
{"id": "Production Support","tags":["Product Development","Business","Communications","Writing","Word","Excel","Power Point","Email","Acrobat","Adobe","Web Development","Office","Outlook"]},
{"id": "Property Manager","tags":["Real estate","Business","Communications","Office","Management","Legal"]},
{"id": "Receptionist","tags":["Speech","Office","Excel","Communications","Project","Reporting","Writing","Word","Power Point","Outlook","Telemarketing"]},
{"id": "Recreational Director","tags":["Entertainment","Communications","Relationships","Networking","Management","Time Management","Decorating"]},
{"id": "Relocation Manager","tags":["Communication","Networking","Relationships","Business","Management","International","Time Management"]},
{"id": "Research Specialist","tags":["Analysis","Communications","Computing","Management","Office","Reporting","Technology","White Paper","Access","Excel","Power Point","Crystal Reports"]},
{"id": "Sales Engineer","tags":["Negotiating","Finance","Business","Market Research","Analysis","Networking","Relationships","Sales","Communications","Technology","Software Support","Power Point","Outlook"]},
{"id": "Sales Manager","tags":["Business","HR","Sales","Communications","Time Management","Management","Public Speaking","Excel","Access","Outlook","Office","Email","Networking"]},
{"id": "Sales Promotion Mgr.","tags":["Negotiating","Finance","Business","Market Research","Analysis","Networking","Relationships","Sales","Communications","Time Management","Adobe","Power Point","Excel"]},
{"id": "Sales Representative","tags":["Negotiating","Finance","Business","Market Research","Analysis","Networking","Relationships","Sales","Communications","List Building","Adobe","Power Point","Excel"]},
{"id": "Sales Trainer","tags":["Sales","Communications","Negotiating","Relationships","Psychology","Telemarketing","Technology","Content Management","Public speaking","Call Center"]},
{"id": "Salesperson","tags":["Negotiating","Finance","Business","Market Research","Networking","Relationships","Sales","Communications","List Building","Adobe","Power Point","Excel","Office"]},
{"id": "Secretary","tags":["Office","Excel","Communications","Project","Writing","Word","Power Point"]},
{"id": "Securities Analyst","tags":["Analysis","Accounting","Communications","Excel","Finance","Investing","Market Research","Modeling","Negotiating","Office","Power Point","Reporting","Technical Analysis"]},
{"id": "Security Consultant","tags":["Psychology"]},
{"id": "Security Director","tags":["Management","Psychology","Communications","Legal","Coach","HR"]},
{"id": "Special Events Manager","tags":["Communications","Time Management","Management","Social Media","Business","Negotiating","Networking","List Building","B2B","Power Point","Outlook","Email","Word"]},
{"id": "Sports Event Manager","tags":["Communications","Time Management","Management","Social Media","Business","Negotiating","Networking","List Building","B2B","Power Point","Outlook","Email","Word"]},
{"id": "Stockbroker","tags":["FX","Business","International","Finance","Negotiating","Relationships","Communication","Analysis","Investing","Analysis","Technical Analysis","Networking","Sales"]},
{"id": "Tax Specialist","tags":["Accounting","Analysis","Business","Computing","Finance","Investing","Legal","Networking","Office","Outlook","Project","QuickBooks","Reporting"]},
{"id": "Telecom Analyst","tags":["Analysis","Call Center","Business","Technology","Networks","MySQL","Networks","TCP/IP","Telemarketing"]},
{"id": "Telemarketer","tags":["Call Center","Business","Telemarketing","Sales","Marketing"]},
{"id": "Title Examiner","tags":["Real estate","Business","Legal"]},
{"id": "Tour Escort","tags":["International","Communications","Business","Ecommerce","Relationships","Networking","Literature","PayPal"]},
{"id": "Tour Guide Director","tags":["International","Communications","Management","Business","Ecommerce","Relationships","Networking","Literature","PayPal","Marketing","Sales"]},
{"id": "Travel Agent","tags":["International","Communications","Management","FX","Business","Ecommerce","Relationships","Email","Outlook","Word","Marketing"]},
{"id": "Underwriter","tags":["Accounting","Business","Computing","Excel","Finance","Legal","Management","Networking","Options","Power Point","Office","Project"]},
{"id": "Works Director","tags":["Recruitment","Public Speaking","Management","Office","Time Management","Project","Outlook","Email"]},
{"id": "Bankruptcy Attorney","tags":["Legal","Networking","Negotiating","Communications","Time Management"]},
{"id": "Border Patrol Agent","tags":["Fitness"]},
{"id": "Correctional Officer","tags":["Coach","Communications","Energy","Fitness","Management","Physical Improvements","Psychology"]},
{"id": "Detective","tags":["Analysis","Anatomy","Athletics","Legal","Management","Psychology","Physical Improvements","Recruitment","Relationships","Technology"]},
{"id": "Development Officer","tags":["Networking","Negotiating","Grants","Fund Raising","Communications","Relationships"]},
{"id": "Hearing Officer","tags":["Legal","Communications","Analysis"]},
{"id": "Homeland Security Officer","tags":["Fitness","Legal"]},
{"id": "International Lawyer","tags":["Business","Communications","Ecommerce","Finance","International","Legal","Negotiating","Networking"]},
{"id": "Investigator","tags":["Analysis","Legal","Communications"]},
{"id": "Law Enforcement Officer","tags":["Communications","Legal","Management","Negotiating","Physical Improvements"]},
{"id": "Lawyer","tags":["Legal","LSAT"]},
{"id": "Legal Nurse Consultant","tags":["Legal","LSAT","Anatomy","Pharmacy","Physiology"]},
{"id": "Legal Secretary","tags":["Chrome","Computing","Communications","Email","Evernote","Power Point","Project","Reporting","Word","Legal","Access","Time Management","LSAT"]},
{"id": "Paralegal","tags":["Legal","LSAT"]},
{"id": "Parole Officer","tags":["Energy","Physical Improvements"]},
{"id": "Private Investigator","tags":["Legal","Networking","Negotiating","Photography"]},
{"id": "Probation Officer","tags":["Legal"]},
{"id": "Baker/Pastry Chef","tags":["Diet","Nutrition","Baking"]},
{"id": "Chef/Gourmet Chef","tags":["Diet","Nutrition","Vegan"]},
{"id": "Pastry Sous Chef","tags":["Diet","Nutrition","Baking"]},
{"id": "Restaurant Manager","tags":["Management","Communications","Nutrition","Business","Real estate","Marketing","Time Management","Accounting","QuickBooks","B2B","Accounting","Social Media","Facebook"]},
{"id": "Viticulturist","tags":["Management","Science","Aquaponic Gardening"]},
{"id": "Winemaker","tags":["Beer Making","Science","Time Management","International"]},
{"id": "Child Care Manager","tags":["Coach","Tutor","Nutrition","Psychology","Teaching","Education"]},
{"id": "Day Care Counselor","tags":["Education","Teaching","Women","Tutor","Self Confidence","Mediation"]},
{"id": "Education Admin.","tags":["Teaching","Tutor","Education"]},
{"id": "Preschool Management","tags":["Teaching","Tutor","Education","Management"]},
{"id": "Preschool Teacher","tags":["Teaching","Education","Tutor","Communications","Coach"]},
{"id": "Professor/Instructor","tags":["Teaching","Education","Tutor","Communications","Coach"]},
{"id": "Rabbi/Minister","tags":["Public Speaking","Communications","Relationships"]},
{"id": "Special Ed. Teacher","tags":["Teaching","Education","Tutor","Communications","Coach"]},
{"id": "Teacher","tags":["Teaching","Education","Tutor","Communications","College Admission"]},
{"id": "University Administrator","tags":["Teaching","Education","Tutor","Communications","Excel","Outlook","Office","Power point","Project","Time Management","Scholarship","Career Improvement"]},
{"id": "University Dean","tags":["Teaching","Education","Tutor","Communications","Excel","Outlook","Office","Power point","Project","Time Management","Scholarship","Management"]},
{"id": "Geologist","tags":["Physiology","Reporting","Science","White Paper","Word","Writing","Analysis","Real estate","Photography"]},
{"id": "Addictions Counselor","tags":["Self Confidence","Medicine","Marijuana","Detox","Psychology","Pharmacy","Smoking"]},
{"id": "Biofeedback Specialist","tags":["Anatomy","Athletics","Communications","Fitness","Massage","Medicine","Nutrition","Psychology","Physical Improvements","Pilates","Relationships","Tai Chi","Teaching"]},
{"id": "Cardiology Technologist","tags":["Analysis","Nutrition","Reporting","Science","White Paper","Word","Writing","Physiology","Anatomy","Smoking"]},
{"id": "Certified Nurse","tags":["Anatomy","Pharmacy","Medicine","Physical Improvements","Healing","Energy","Nutrition","Physiology"]},
{"id": "Certified Nurse Aide","tags":["Anatomy","Pharmacy","Medicine","Physical Improvements","Healing","Energy","Nutrition","Physiology"]},
{"id": "Chemical Dependency Spec.","tags":["Medicine","Pharmacy","Marijuana","Detox","Smoking"]},
{"id": "Chiropractor","tags":["Anatomy","Physical Improvements","Healing","Energy","Physiology"]},
{"id": "Clinical Medical Assistant","tags":["Communications","Office","Word","Excel"]},
{"id": "Clinical Rsch. Asst.","tags":["Analysis","Reporting","Writing","Word"]},
{"id": "Dental Assistant","tags":["Anatomy","Medicine","Physical Improvements","Healing","Energy","Physiology","Office"]},
{"id": "Dental Hygienist","tags":["Anatomy","Medicine","Physical Improvements","Healing","Energy","Physiology"]},
{"id": "Dentist","tags":["Anatomy","Medicine","Physical Improvements","Healing","Energy","Physiology","Communications"]},
{"id": "Ekg Technician","tags":["medicine","healing","physiology","anatomy"]},
{"id": "Family Counseling Mgr.","tags":["Communication","Coach","Psychology","Self confidence","relationships","public speaking","speech"]},
{"id": "Geriatric Specialist","tags":["Medicine","Diet","Physical Improvements","Weight Loss","Communication","Anatomy","Fitness","Nutrition"]},
{"id": "Gerontologist","tags":["Communication","Coach","Psychology","Relationships","Public Speaking","Diet"]},
{"id": "Health Care Manager","tags":["Communication","Public Speaking","Management","Time Management","Psychology","Medicine","Healing"]},
{"id": "Health Care Reimbursement Specialist","tags":["Communication","Office","Excel","Word","Analysis","Email"]},
{"id": "Health Claims Examiner","tags":["Communication","Accounting","Office","Excel","Word","Analysis","Email","Reporting","Medicine","Anatomy"]},
{"id": "Health Information Technician","tags":["Analysis","Computing","Content Management","Data Storage","Management","Medicine","Office","Technology"]},
{"id": "Health Svc. Administrator","tags":["Medicine","Diet","Physical Improvements","Weight Loss","Communication","Anatomy","Fitness","Nutrition","Management","Time Management"]},
{"id": "Health Therapist","tags":["Communication","Coach","Psychology","Self Confidence","Relationships","Public Speaking","Diet"]},
{"id": "Health Unit Coordinator","tags":["Communications","Computing","Content Management","Management","Reporting","Time Management",""]},
{"id": "HMO Administrator","tags":["Communication","Public Speaking","Management","Time Management","Psychology","Medicine","Healing"]},
{"id": "Hospital Administrator","tags":["Communication","Public Speaking","Management","Time Management","Psychology","Medicine","Healing"]},
{"id": "Medical Assistant","tags":["Medicine","Physical Improvements","Weight Loss","Communication","Anatomy","Fitness"]},
{"id": "Medical Coding & Billing Specialist","tags":["Office","Excel","Email","Accounting","Reporting"]},
{"id": "Medical Office Assistant","tags":["Communications","Computing","Content Management","Medicine","Office","Reporting","Technology"]},
{"id": "Medical Secretary","tags":["Medicine","Office","Excel","Communications","Project","Reporting","Market Research","Analysis","Writing","Word","Power Point"]},
{"id": "Medical Technician","tags":["Medicine","Physical Improvements","Weight Loss","Communication","Anatomy","Fitness"]},
{"id": "Mental Health Counselor","tags":["Medicine","Diet","Physical Improvements","Weight Loss","Communication","Anatomy","Fitness","Nutrition"]},
{"id": "Nursing Administrator","tags":["Anatomy","Communications","Management","Medicine","Nutrition","Physiology","Psychology","Technology","Time Management"]},
{"id": "Occupational Therapist","tags":["Medicine","Diet","Physical Improvements","Weight Loss","Communication","Anatomy","Fitness","Nutrition"]},
{"id": "Optical Technician","tags":["Medicine","Healing","Pharmacy","Healing","Energy"]},
{"id": "Optometrist","tags":["Medicine","Healing","Pharmacy","Healing","Energy"]},
{"id": "Outplacement Counselor","tags":["Communication","Coach","Psychology","Self Confidence","Relationships","Public Speaking"]},
{"id": "Patient Care Technician","tags":["Healing","Communication","Coach","Psychology","Relationships","Medicine","Diet"]},
{"id": "Pharmacist","tags":["Medicine","Healing","Pharmacy","Detox"]},
{"id": "Pharmacy Technician","tags":["Medicine","Healing","Pharmacy"]},
{"id": "Physician","tags":["Anatomy","Pharmacy","Medicine","Physical Improvements","Healing","Energy","Nutrition","Physiology","Psychology","Detox"]},
{"id": "Physician's Assistant","tags":["Medicine","Diet","Physical Improvements","Communication","Anatomy","Fitness","Nutrition","Healing"]},
{"id": "Podiatrist","tags":["Anatomy","Medicine","Physical Improvements","Healing","Energy","Physiology"]},
{"id": "Radiologic Technician","tags":["Medicine","Healing","Physiology","Anatomy"]},
{"id": "Radiology Manager","tags":["Medicine","Healing","Physiology","Anatomy","Management"]},
{"id": "Registered Nurse","tags":["Anatomy","Pharmacy","Medicine","Physical Improvements","Healing","Energy","Nutrition","Physiology","Psychology"]},
{"id": "Rehabilitation Counselor","tags":["Self Confidence","Medicine","Relationships","Detox","Psychology","Physical Improvements","Nutrition","Smoking"]},
{"id": "Speech Pathologist","tags":["Medicine","Healing","Public Relations","Public Speaking","Speech"]},
{"id": "Stress Reduction Spec.","tags":["Self Confidence","Psychology","Medicine","Nutrition","Healing","Energy"]},
{"id": "Veterinarian","tags":["Canine","Medicine","Diet","Physical Improvements","Weight Loss","Communication","Anatomy","Fitness","Nutrition"]},
{"id": "X-Ray Technician","tags":["Analysis","Anatomy","Computing","Hardware","Medicine","Science","Technology"]},
{"id": "Actuary","tags":["Math","Business","Technical Analysis","Modeling","Market Research","Accounting","Finance","Macros","Analysis"]},
{"id": "Agricultural Inspector","tags":["Analysis","Nutrition","Reporting","Science","White Paper","Word","Writing","Physiology"]},
{"id": "Agricultural Scientist","tags":["Analysis","Nutrition","Reporting","Science","White Paper","Word","Writing","Physiology"]},
{"id": "Anthropologist","tags":["Analysis","Reporting","Science","Physiology","White Paper","Writing","Word"]},
{"id": "Astronomer","tags":["Cosmometry","Physics","Math"]},
{"id": "Author","tags":["Blog","Content Development","Content Management","Copywriting","Course Development","Education","Email","Film","Publishing","Literature","Word","WordPress","Writing"]},
{"id": "Biologist","tags":["Physiology","Science","White Paper","Word","Writing"]},
{"id": "Biotech. Researcher","tags":["Anatomy","Medicine","Nutrition","Psychology","Physical Improvements","Healing","Energy","Thyroid"]},
{"id": "Chemical Engineer","tags":["Physiology","Science","White Paper","Word","Writing","Analysis","Math","Physics"]},
{"id": "Chemist","tags":["Physiology","Medicine","Science","White Paper","Word","Writing","Analysis"]},
{"id": "City Housing Manager","tags":["B2B","Communications","Time Management","Construction","Content Development","Industrial","Management"]},
{"id": "City Manager","tags":["Management","Finance","Business","Communications","Construction","Design","Accounting","Industrial","Legal","Negotiating","Networking","Office","Outsource"]},
{"id": "Community Affairs Mgr.","tags":["B2B","Blog","Branding","Business","Career Improvement","Coach","College Admission","Communications","Email","Evernote","Excel","Fund Raising","Management"]},
{"id": "Community Support Worker","tags":["Career Improvement","Coach","College Admission","Communications","Relationships","Psychology","Recruitment"]},
{"id": "Editor","tags":["Blog","Content Development","Content Management","Copywriting","Course Development","Education","Email","Film","Publishing","Literature","SEM","SEO","Social Media"]},
{"id": "Environmental Analyst","tags":["Fishing","Physiology","Reporting","Science","White Paper","Word","Writing","Legal"]},
{"id": "Environmental Attorney","tags":["Architecture","Construction","Industrial","Market Research","Negotiating","Office","Physics","Public Speaking","Real estate","Science","Time Management","Legal"]},
{"id": "Environmental Specialist","tags":["Fishing","Physiology","Science","White Paper","Word","Writing","White Paper"]},
{"id": "Fish/Wildlife Specialist","tags":["Fishing","Physiology","Science","White Paper","Word","Writing","White Paper"]},
{"id": "Forestry Technician","tags":["Fishing","Physiology","Science","White Paper","Word","Writing"]},
{"id": "Freelance Writer","tags":["Blog","Content Development","Content Management","Copywriting","Course Development","Education","Email","Film","Publishing","Literature","SEM","SEO","Social Media"]},
{"id": "Hazardous Waste Mgr.","tags":["Fishing","Physiology","Science","White Paper","Word","Writing","Legal","Email","Outlook","Communications"]},
{"id": "Horticulturist","tags":["Science","Physiology","Aquaponic Gardening"]},
{"id": "Interpreter","tags":["Communications","Public Speaking","Serbian","Speech","Writing","International","Brazilian Portuguese"]},
{"id": "Lab Technician","tags":["Thyroid","Physics","Pharmacy","Medicine","Healing","Anatomy"]},
{"id": "Library Manager","tags":["Content Management","Digital Content","Education","Joomla","Kindle","Amazon","Literature","Office","Publishing"]},
{"id": "Lobbyist","tags":["B2B","Blog","Branding","Business","Career Improvement","Coach","College Admission","Communications","Email","Evernote","Excel","Fund Raising","Management"]},
{"id": "Marine Biologist","tags":["Fishing","Reporting","Science","White Paper","Word","Writing"]},
{"id": "Mathematician","tags":["Access","Accounting","Act Math","Analysis","Computing","Crystal Reports","Market Research","Math","Modeling","Reporting","Science","Technical Analysis","Options"]},
{"id": "Meteorologist","tags":["Communications","Math","Physics","Reporting","Science","Technology"]},
{"id": "Microbiologist","tags":["Physiology","Reporting","Science"]},
{"id": "Nuclear Engineer","tags":["Crystal Reports","Math","Physics","Physiology","Reporting","Science","Technology"]},
{"id": "Nuclear Specialist","tags":["Crystal Reports","Math","Physics","Reporting","Science","Technology"]},
{"id": "Oceanographer","tags":["Content Development","Communications","Crystal Reports","Math","Physics","Reporting","Science","Technology"]},
{"id": "Park Ranger","tags":[""]},
{"id": "Petroleum Engineer","tags":["Architecture","Construction","Industrial","Physics","Public Speaking","Science"]},
{"id": "Physicist","tags":["3D Modeling","3Ds Max","Content Development","Crystal Reports","Illustrator","Math","Physics","Publishing","Reporting","Science","Software","Technology"]},
{"id": "Planning Specialist","tags":["Project","Negotiating","Office","Public Speaking","Relationships","Business","Time Management","Outsource","Networking","Management","Power Point"]},
{"id": "Political Analyst","tags":["Communications","Fund Raising","Legal","Market Research","Math"]},
{"id": "Political Scientist","tags":["Communications","Legal","Market Research","Math","Reporting"]},
{"id": "Politician","tags":["B2B","Blog","Branding","Business","Career Improvement","Coach","Communications","Email","Fund Raising","Management","Market Research","Time Management","Negotiating"]},
{"id": "Public Administrator","tags":["Communications","International","Management","Market Research","Negotiating","Networking","Public Speaking","Relationships","PR"]},
{"id": "Public Relations Spec.","tags":["B2B","Blog","Branding","Business","Career Improvement","College Admission","Communications","Email","Evernote","Fund Raising","Marketing","Market Research","Negotiating"]},
{"id": "Sanitation Engineer","tags":["Architecture","Construction","Industrial","Physics","Public Speaking","Real-estate","Science"]},
{"id": "Scientific Programmer","tags":["Bgp","C Language","C++","Cocoa","Computing","Dreamweaver","E4X","Html","Java Swing","JavaScript","Mac","Networks","Online"]},
{"id": "Scientific Writer","tags":["Copywriting","Course Development","Education","Email","Publishing","Literature","Word","Wordpress","Writing","White Paper"]},
{"id": "Social Director","tags":["Wedding","TV Appearance","Relationships","Coach","Communications","Entertainment","Film"]},
{"id": "Social Researcher","tags":["Social Media","Facebook","Twitter","LinkedIn","Google","Marketing","Market Research","Analysis","International","Psychology"]},
{"id": "Social Scientist","tags":["Social Media","Facebook","Twitter","LinkedIn","Google","Marketing","Market Research","Analysis","International","Psychology"]},
{"id": "Social Worker","tags":["Coach","Communications","Relationships","Psychology","Self Confidence"]},
{"id": "Sociologist","tags":["Science","Social Media","Psychology","Art","Communications","International","Men","Women","Relationships"]},
{"id": "Soil Scientist","tags":["Science","Reporting","Excel","Crystal Reports"]},
{"id": "Speech Writer","tags":["Content Development","Content Management","Copywriting","Course Development","Education","Speech","Word","Wordpress","Writing"]},
{"id": "Statistician","tags":["Access","Accounting","Act Math","Computing","Crystal Reports","Market Research","Math","Modeling","Reporting","Science","Technical Analysis","Options","Macros"]},
{"id": "Surveyor","tags":["Architecture","Construction","Industrial","Market Research","Office","Real estate","Acrobat","3D Modeling","3DS Max","AutoCAD","Photography"]},
{"id": "Technical Writer","tags":["Blog","Content Development","Copywriting","Education","Email","Publishing","Word","Writing","White Paper","Technology"]},
{"id": "Translator","tags":["Content Development","Copywriting","Speech","Word","Writing","Brazilian Portuguese","Serbian"]},
{"id": "Tree Surgeon","tags":["Science","Aquaponic Gardening"]},
{"id": "Union Representative","tags":["Career Improvement","Coach","Communications","Email","Evernote","Excel","Fund Raising","Management","Marketing","Market Research","Negotiating","Networking","Office"]},
{"id": "Writer  ","tags":["Blog","Content Development","Content Management","Copywriting","Course Development","Education","Email","Film","Publishing","Literature","SEM","SEO","Social Media"]},
{"id": "Athletic/Pro. Coach","tags":["Anatomy","Athletics","Communications","Fitness","Massage","Medicine","Nutrition","Psychology","Physical Improvements","Relationships","Teaching","Coaching","Meditation"]},
{"id": "Dietitian","tags":["Anatomy","Athletics","Fitness","Medicine","Nutrition","Psychology","Physical Improvements","Vegan","Healing","Energy","Detox","Diet"]},
{"id": "Fitness Consultant","tags":["Anatomy","Athletics","Communications","Fitness","Massage","Medicine","Nutrition","Psychology","Physical Improvements","Pilates","Relationships","Tai Chi","Teaching"]},
{"id": "Fitness Instructor","tags":["Anatomy","Athletics","Communications","Fitness","Massage","Medicine","Nutrition","Psychology","Physical Improvements","Pilates","Relationships","Tai Chi","Teaching"]},
{"id": "Health Fitness Specialist","tags":["Anatomy","Athletics","Communications","Fitness","Massage","Medicine","Nutrition","Psychology","Physical Improvements","Pilates","Relationships","Tai Chi","Teaching"]},
{"id": "Holistic Health Practitioner","tags":["Anatomy","Athletics","Communications","Fitness","Massage","Medicine","Nutrition","Psychology","Physical Improvements","Pilates","Relationships","Tai Chi","Teaching"]},
{"id": "Massage Therapist","tags":["Anatomy","Athletics","Fitness","Massage","Medicine","Nutrition","Psychology","Physical Improvements","Pilates","Tai Chi","Vegan","Healing","Energy"]},
{"id": "Nutritionist","tags":["Anatomy","Fitness","Medicine","Nutrition","Psychology","Physical Improvements","Vegan","Healing","Coaching","Energy"]},
{"id": "Personal Fitness Trainer","tags":["Anatomy","Athletics","Communications","Fitness","Massage","Medicine","Nutrition","Psychology","Physical Improvements","Pilates","Relationships","Tai Chi","Teaching"]},
{"id": "Physical Therapist","tags":["Anatomy","Athletics","Communications","Fitness","Massage","Medicine","Nutrition","Psychology","Physical Improvements","Pilates","Relationships","Tai Chi","Teaching"]},
{"id": "Professional Athlete","tags":["Athletics","Communications","Fitness","Massage","Nutrition","Psychology","Physical Improvements","Pilates","Relationships","Tai Chi","Vegan","Coaching","Meditation"]},
{"id": "Trainer","tags":["Anatomy","Athletics","Communications","Fitness","Massage","Medicine","Nutrition","Psychology","Physical Improvements","Relationships","Teaching","Coaching","Meditation"]},
{"id": "A+ Certified Configuration Associate","tags":["AJAX","Apps","CCNP","Chrome","Cloud Computing","Data Storage","Dreamweaver","Excel","Hardware","HTML","iOS","IPv4","Java Swing"]},
{"id": "Biomedical Engineer","tags":["Analysis","Anatomy","Healing","Medicine","Pharmacy","Physiology","Thyroid","Hardware","xCode","Interview","Reporting","Crystal Reporting"]},
{"id": "Cisco Certified Operations Technician","tags":["Cisco","CCNP","Cloud Computing","Communications","Networks","Online Security","Programming","Software Support","TCP/IP","Technology","TSHOOT","Node.js"]},
{"id": "Cisco Network Engineer","tags":["Cisco","CCNP","Cloud Computing","Communications","Networks","Online Security","Programming","Software Support","TCP/IP","Technology","TSHOOT","Node.js"]},
{"id": "Computer Engineer","tags":["AJAX","Apps","CCNP","Chrome","Cloud Computing","Data Storage","Dreamweaver","Excel","Hardware","HTML","iOS","IPv4","Java Swing"]},
{"id": "Computer Hardware Technician","tags":["AJAX","Apps","CCNP","Chrome","Cloud Computing","Data Storage","Dreamweaver","Excel","Hardware","HTML","iOS","IPv4","Java Swing"]},
{"id": "Computer Operator","tags":["Cisco","CCNP","Cloud Computing","Communications","Networks","Online Security","Programming","Software Support","TCP/IP","Technology","TSHOOT","Node.js","Email"]},
{"id": "Computer Programmer","tags":["Ajax","BGP","C Language","C++","Cocoa","Computing","Dreamweaver","E4X","HTML","Java Swing","JavaScript","Mac","Networks"]},
{"id": "Computer Support Specialist","tags":["AJAX","Apps","CCNP","Chrome","Cloud Computing","Data Storage","Dreamweaver","Excel","Hardware","HTML","iOS","IPv4","Java Swing"]},
{"id": "Computer Systems Technician","tags":["AJAX","Apps","CCNP","Chrome","Cloud Computing","Data Storage","Dreamweaver","Excel","Hardware","HTML","iOS","IPv4","Java Swing"]},
{"id": "Computer Technical Support Help Desk","tags":["AJAX","Apps","CCNP","Chrome","Cloud Computing","Data Storage","Dreamweaver","Excel","Hardware","HTML","iOS","IPv4","Java Swing"]},
{"id": "Construction Engineer","tags":["AutoCAD","3D Modeling","3DS Max","Design","Industrial","Product Development","Construction"]},
{"id": "Engineer Technician","tags":["AutoCAD","3D Modeling","3DS Max","Design","Industrial","Product Development","Architecture","Communications","Time Management","Office","Construction","Illustrator"]},
{"id": "Environmental Engineer","tags":["Architecture","Construction","Industrial","Market Research","Negotiating","Office","Physiology","Physics","Public Speaking","Real estate","Science","Time Management","Physiology"]},
{"id": "Help Desk Technician","tags":["Apps","Chrome","Cloud Computing","Data Storage","Excel","Hardware","Mac","Mobile","MySQL","Networks","Office","Online","Online Security"]},
{"id": "It Support Specialist","tags":["Apps","Chrome","Cloud Computing","Data Storage","Excel","Hardware","Mac","Mobile","MySQL","Networks","Office","Online","Online Security"]},
{"id": "Mechanical Engineer","tags":["3D Modeling","3DS Max","Architecture","Computing","Design","Digital Design","Management","Physics","Technology"]},
{"id": "Network Admin","tags":["Apps","Chrome","Cloud Computing","Data Storage","Excel","Hardware","Mac","Mobile","Networks","Office","Online","Online Security","OS X Lion"]},
{"id": "Network Engineer","tags":["Apps","Chrome","Cloud Computing","Data Storage","Excel","Hardware","Mac","Mobile","Networks","Office","Online","Online Security","OS X Lion"]},
{"id": "PC Support Specialist","tags":["Apps","Chrome","Cloud Computing","Data Storage","Excel","Hardware","Mac","Mobile","MySQL","Networks","Office","Online","Online Security"]},
{"id": "Software Engineer","tags":["C++","C Language","JavaScript","Networking","MySQL","Cocoa","Math","Software Development","Software Support","xCode","iOS","JavaScript","Ruby"]},
{"id": "Systems Analyst","tags":["C++","C Language","JavaScript","Networking","MySQL","Cocoa","Math","Software Development","Software Support","Analysis"]},
{"id": "Systems Engineer","tags":["C++","C Language","JavaScript","Networking","MySQL","Cocoa","Math","Software Development","Software Support."]},
{"id": "Systems Programmer","tags":["AJAX","Apps","CCNP","Chrome","Cloud Computing","Data Storage","Dreamweaver","Excel","Hardware","HTML","iOS","IPv4","Java Swing"]},
{"id": "Webmaster","tags":["3D Modeling","3DS Max","Acrobat","Adobe","Android","Chrome","Cloud Computing","Computing","Content Development","Content Management","Data Storage","Design","Digital Content"]},
{"id": "AC & Refrigeration Technician","tags":["Freight","Forklift"]},
{"id": "Animal Trainer","tags":["Animal Training","Canine","Veterinary"]},
{"id": "Appraiser","tags":["Analysis","Broker","DSLR","Email","Acrobat","Adobe","Market Research","Photography","Real estate","Writing","Math","Reporting"]},
{"id": "Auto Repair Technician","tags":[""]},
{"id": "Building Contractor","tags":["Architecture","B2B","Business","Communications","Construction","Design","Accounting","Industrial","Legal","Negotiating","Networking","Office","Outsource"]},
{"id": "Building Inspector","tags":["Architecture","B2B","Business","Communications","Construction","Industrial","Legal","Negotiating","Office","Project","Real estate","Time Management"]},
{"id": "Building Manager","tags":["Management","Finance","Business","Communications","Construction","Design","Accounting","Industrial","Legal","Negotiating","Networking","Office","Outsource"]},
{"id": "Cashier","tags":["Math","Communications","Business"]},
{"id": "Ceramic Engineer","tags":["3D Modeling","3DS Max","Design","Industrial","Product Development"]},
{"id": "Courier","tags":["Athletics","Freight"]},
{"id": "Developer","tags":["AJAX","Apps","CCNP","Chrome","Cloud Computing","Data Storage","Dreamweaver","Excel","Hardware","HTML","iOS","IPv4","Java Swing"]},
{"id": "Electrical Designer","tags":["AutoCAD","3D Modeling","3DS Max","Design","Industrial","Product Development","Architecture","Communications","Construction"]},
{"id": "Electrical Engineer","tags":["AutoCAD","3D Modeling","3DS Max","Design","Industrial","Product Development","Architecture","Communications","Time Management","Office","Construction","Illustrator"]},
{"id": "Electronics Engineer","tags":["AutoCAD","3D Modeling","3DS Max","Design","Industrial","Product Development","Architecture","Communications","Time Management","Office","Construction","Illustrator"]},
{"id": "Electro-optical Engineer","tags":["AutoCAD","3D Modeling","3DS Max","Design","Industrial","Product Development","Architecture","Communications","Time Management","Office","Construction","Illustrator"]},
{"id": "Estimator","tags":["Analysis","Acrobat","Adobe","Market Research","Math","Computing","Real estate","Writing","Excel","Access","Reporting","Project","Word"]},
{"id": "Facilities Manager","tags":["Management","Finance","Business","Communications","Construction","Design","Accounting","Industrial","Legal","Negotiating","Networking","Office","Outsource"]},
{"id": "Fast Food Manager","tags":["Management","Finance","Business","Communications","Accounting","Networking","Office","Outsource","Project","Time Management","QuickBooks","Communications"]},
{"id": "Gemologist","tags":["Science","Physiology"]},
{"id": "Groundskeeper","tags":["Aquaponic Gardening","Athletics"]},
{"id": "Hvac Maintenance Technician","tags":["Construction"]},
{"id": "International Courier","tags":["Athletics","Freight","International"]},
{"id": "Land Developer","tags":["Architecture","B2B","Business","Communications","Construction","Design","Accounting","Industrial","Legal","Negotiating","Networking","Office","Outsource"]},
{"id": "Metallographic Technician","tags":["Analysis","Architecture","Construction","Industrial","Technology"]},
{"id": "Metallurgical Engineer","tags":["Energy","Physics","Science","Math","Analysis","Modeling"]},
{"id": "Motorcycle Technician Specialist","tags":[""]},
{"id": "Quality Control Inspector","tags":["Analysis"]},
{"id": "Railroad Engineer","tags":["Energy","Physics","Science","Math","Analysis","Modeling"]},
{"id": "Real Estate Broker","tags":["Architecture","B2B","Business","Communications","Construction","Design","Accounting","Industrial","Legal","Negotiating","Networking","Office","Outsource"]},
{"id": "Redevelopment Specialist","tags":["Project","Management","Time Management","Negotiating","Analysis","Relationships","Communication"]},
{"id": "Retail Store Manager","tags":["HR","sales","business","Communications","Time Management","Content Development","management","Public Speaking"]},
{"id": "Safety Engineer","tags":["Management","Architecture","Math","Science"]},
{"id": "Seminar Presenter","tags":["Communications","Networking","Business","PowerPoint","Analysis","Self Confidence","Public Speaking","Psychology"]},
{"id": "Service Manager","tags":["HR","Communications","Time Management","Content Development","management","Public Speaking",""]},
{"id": "Structural Engineer","tags":["AutoCAD","3D Modeling","3DS Max","Design","Industrial","Product Development","Architecture","Communications","Time Management","Office","Construction","Illustrator"]},
{"id": "Traffic Manager","tags":["Social Media","Google","SEO","SEM","Management","Marketing","Market Research","Sales","Analysis","Finance","Technical Analysis","YouTube","Facebook"]},
{"id": "Workshop Presenter","tags":["Public Speaking","Excel","PowerPoint","Psychology","Communications","Fund Raising","Business","Digital Content","Content Management","Speech"]}
];