var oldprofessions = [
{ "profession": "Accountant and Auditor - 134" },
{ "profession": "Accountant and Auditor - 140" },
{ "profession": "Actor" },
{ "profession": "Actuary" },
{ "profession": "Adhesive Bonding Machine Operator" },
{ "profession": "Adjudicator" },
{ "profession": "Adult Basic Education Teacher" },
{ "profession": "Advertising Manager" },
{ "profession": "Advertising Sales Agent" },
{ "profession": "Aerospace engineer" },
{ "profession": "Aerospace Engineering Technician" },
{ "profession": "Agricultural and Food Science Technician" },
{ "profession": "Agricultural engineer" },
{ "profession": "Agricultural Equipment Operator" },
{ "profession": "Agricultural Inspector" },
{ "profession": "Agricultural Manager" },
{ "profession": "Air Traffic Controller" },
{ "profession": "Aircraft Cargo Handling Supervisor" },
{ "profession": "Aircraft part assembler" },
{ "profession": "Airfield Operations Specialist" },
{ "profession": "Airline Pilot Flight Instructor" },
{ "profession": "Ambulance Dispatcher" },
{ "profession": "Ambulance Drivers and Attendant" },
{ "profession": "Anesthesiologist - 326" },
{ "profession": "Anesthesiologist - 65" },
{ "profession": "Animal Caregiver" },
{ "profession": "Animal Control Officer" },
{ "profession": "Animal Scientist" },
{ "profession": "Animal Trainer" },
{ "profession": "Anthropologists and Archeologist" },
{ "profession": "Appliance Service Technician" },
{ "profession": "Applications Software Developer" },
{ "profession": "Aquaculture Worker" },
{ "profession": "Arbitrator, Mediator, and Conciliator" },
{ "profession": "Architect" },
{ "profession": "Architectual and Engineering Manager" },
{ "profession": "Architectural and Civil Drafter" },
{ "profession": "Archivist" },
{ "profession": "Art Director" },
{ "profession": "Astronomer" },
{ "profession": "Athlete" },
{ "profession": "Athletic Trainer" },
{ "profession": "Atmospheric Scientist" },
{ "profession": "Audio and Video Equipment Technician - 242" },
{ "profession": "Audio and Video Equipment Technician - 274" },
{ "profession": "Audiologist" },
{ "profession": "Auto Body Repair Technician" },
{ "profession": "Auto Cleaner" },
{ "profession": "Auto Insurance Appraiser" },
{ "profession": "Automotive and Watercraft Service Attendant" },
{ "profession": "Automotive Paint Technician" },
{ "profession": "Avionics Technician" },
{ "profession": "Baggage Porter" },
{ "profession": "Bailiff" },
{ "profession": "Baker" },
{ "profession": "Barber" },
{ "profession": "Bartender" },
{ "profession": "Bicycle Repairman" },
{ "profession": "Billing Clerk" },
{ "profession": "Biochemist and Biophysicist" },
{ "profession": "Biological Technician" },
{ "profession": "Biomedical Engineer" },
{ "profession": "Boiler operator" },
{ "profession": "Boilermaker" },
{ "profession": "Brick and Block Mason" },
{ "profession": "Bricklayer Helper" },
{ "profession": "Bridge and Lock Tender" },
{ "profession": "Broadcast News Analyst" },
{ "profession": "Broadcast Technician" },
{ "profession": "Budget Analyst" },
{ "profession": "Butcher" },
{ "profession": "C Level Executive Officer" },
{ "profession": "Cabinetmaker" },
{ "profession": "Camera Operator" },
{ "profession": "Captains, Mates, and Pilots of Water Vessels" },
{ "profession": "Carpenter" },
{ "profession": "Carpenter's Helper" },
{ "profession": "Carpet Installer" },
{ "profession": "Cartographers and Photogrammetrist" },
{ "profession": "Cashier" },
{ "profession": "Casino Manager" },
{ "profession": "Cement Mason" },
{ "profession": "Central Melt Specialist" },
{ "profession": "Change Person" },
{ "profession": "Chemical Engineer" },
{ "profession": "Chemical Plant and System Operator" },
{ "profession": "Chemical Process Equipment Operator" },
{ "profession": "Chemical Technician" },
{ "profession": "Chemist" },
{ "profession": "Child Care Worker" },
{ "profession": "Chiropractors - 209" },
{ "profession": "Chiropractors - 259" },
{ "profession": "Choreographer" },
{ "profession": "Civil Engineer" },
{ "profession": "Civil Engineering Technician" },
{ "profession": "Clay Modeler" },
{ "profession": "Clean in Places Operator (CIP Operator)" },
{ "profession": "Clergy" },
{ "profession": "Coach and Scout" },
{ "profession": "Coil Winder" },
{ "profession": "Commercial and Industrial Designer" },
{ "profession": "Commercial Pilot - 212" },
{ "profession": "Commercial Pilot - 515" },
{ "profession": "Communications Tower Technician" },
{ "profession": "Community Health Worker" },
{ "profession": "Community Service Manager" },
{ "profession": "Compensation Analyst" },
{ "profession": "Compensation and Benefits Manager" },
{ "profession": "Compliance Officer" },
{ "profession": "Compressor Station Operator" },
{ "profession": "Computer Hardware Engineer - 105" },
{ "profession": "Computer Hardware Engineer - 94" },
{ "profession": "Computer Integrated Manufacturing Operator" },
{ "profession": "Computer Network Architect" },
{ "profession": "Computer Network Support Specialist" },
{ "profession": "Computer Numerically Controlled Machine Tool Programmer" },
{ "profession": "Computer Programmer" },
{ "profession": "Computer Scientist" },
{ "profession": "Computer Support Specialist" },
{ "profession": "Computer Systems Analyst" },
{ "profession": "Computer-Controlled Machine Tool Operator" },
{ "profession": "Concierge" },
{ "profession": "Conservation Scientist" },
{ "profession": "Construction Inspector" },
{ "profession": "Construction Laborer" },
{ "profession": "Construction Manager" },
{ "profession": "Construction Supervisor" },
{ "profession": "Continuous Mining Machine Operator" },
{ "profession": "Conveyor Tender" },
{ "profession": "Correctional Officer" },
{ "profession": "Correctional Officer Captain" },
{ "profession": "Correctional Treatment Specialist" },
{ "profession": "Cost Estimator" },
{ "profession": "Costume Attendant" },
{ "profession": "Counter Clerk" },
{ "profession": "Courier" },
{ "profession": "Craft Artist" },
{ "profession": "Crane and Tower Operator" },
{ "profession": "Credit Analyst" },
{ "profession": "Credit Counselor" },
{ "profession": "Criminal Investigator" },
{ "profession": "Crossing Guard" },
{ "profession": "Crusher Operator" },
{ "profession": "Curator" },
{ "profession": "Customer Service Representative" },
{ "profession": "Cutting Machine Operator" },
{ "profession": "Dancer" },
{ "profession": "Database Administrator" },
{ "profession": "Debt Collector" },
{ "profession": "Delivery services Drivers" },
{ "profession": "Dental Laboratory Technician" },
{ "profession": "Dentist" },
{ "profession": "Derrick Operator" },
{ "profession": "Detective Supervisor" },
{ "profession": "Diagnostic Medical Sonographer" },
{ "profession": "Die Cast Technician" },
{ "profession": "Dietetic Technician" },
{ "profession": "Dietitian and Nutritionist" },
{ "profession": "Dispatcher (Dispatch)" },
{ "profession": "Dredge Operator" },
{ "profession": "Drill Operator" },
{ "profession": "Driller" },
{ "profession": "Drilling and Boring Machine Operator" },
{ "profession": "Driver/Sales Worker" },
{ "profession": "Dry Kiln Operator" },
{ "profession": "Dry Wall Installer" },
{ "profession": "Dye Machine Operator" },
{ "profession": "Earth Moving Equipment Operator" },
{ "profession": "Economist" },
{ "profession": "Editor" },
{ "profession": "Electric Motor Controls Assembler" },
{ "profession": "Electrical and Electronics Drafter" },
{ "profession": "Electrical and electronics engineering technician" },
{ "profession": "Electrical Engineer" },
{ "profession": "Electrician" },
{ "profession": "Electrician's Helper" },
{ "profession": "Electromechanical Equipment Assembler" },
{ "profession": "Electro-Mechanical Technician" },
{ "profession": "Electronics engineer" },
{ "profession": "Elementary School Teacher" },
{ "profession": "Elevator Installer" },
{ "profession": "Emergency Management Director" },
{ "profession": "Engraver" },
{ "profession": "Environmental Engineer" },
{ "profession": "Environmental Engineering Technician" },
{ "profession": "Environmental Science and Protection Technician" },
{ "profession": "Environmental Scientist and Specialist" },
{ "profession": "Epidemiologist" },
{ "profession": "Equipment Operator (EO)" },
{ "profession": "Event Planner" },
{ "profession": "Executive Administrative Assistant" },
{ "profession": "Exercise Physiologist - 205" },
{ "profession": "Exercise Physiologist - 258" },
{ "profession": "Explosive Technician" },
{ "profession": "Extruding and Drawing Machine Operator" },
{ "profession": "Extrusion Operator" },
{ "profession": "Fabric and Apparel Patternmaker" },
{ "profession": "Family and General Practitioner" },
{ "profession": "Family Social Worker" },
{ "profession": "Farm and Home Management Advisor" },
{ "profession": "Farm Labor Contractor" },
{ "profession": "Farm Product Purchasing Agent" },
{ "profession": "Farm Worker" },
{ "profession": "Fashion Designer" },
{ "profession": "Fence Erector" },
{ "profession": "Fiberglasser" },
{ "profession": "Film and Video Editor" },
{ "profession": "Financial Analyst" },
{ "profession": "Financial Examiner" },
{ "profession": "Financial Manager" },
{ "profession": "Fine artist" },
{ "profession": "Fire Fighter" },
{ "profession": "Fire Investigator" },
{ "profession": "Fish and Game Warden" },
{ "profession": "Fish Cutter" },
{ "profession": "Fisherman" },
{ "profession": "Fitness Instructor" },
{ "profession": "Flight Attendant" },
{ "profession": "Floor Layer" },
{ "profession": "Floor Sander" },
{ "profession": "Floral Designer" },
{ "profession": "Food Batchmaker" },
{ "profession": "Food Cooking Machine Operator" },
{ "profession": "Food Dehydrator Operator" },
{ "profession": "Food Scientist" },
{ "profession": "Food Service Manager" },
{ "profession": "Forensic Science Technician" },
{ "profession": "Forest and Conservation Technician" },
{ "profession": "Forester" },
{ "profession": "Forge Operator" },
{ "profession": "Foundry Molder" },
{ "profession": "Freight Conductor" },
{ "profession": "Front Desk Clerk" },
{ "profession": "Fundraiser" },
{ "profession": "Funeral Attendant" },
{ "profession": "Funeral Service Manager" },
{ "profession": "Furniture Finisher" },
{ "profession": "Games Dealer" },
{ "profession": "Gaming Cage Cashier" },
{ "profession": "Gaming Surveillance Officer" },
{ "profession": "Garment Presser" },
{ "profession": "Gas Plant operator" },
{ "profession": "Genetic Counselor" },
{ "profession": "Geographer" },
{ "profession": "Geological and Petroleum Technician" },
{ "profession": "Geoscientist" },
{ "profession": "Glass Cutting Machine Operator" },
{ "profession": "Glazier" },
{ "profession": "Graphic Designer" },
{ "profession": "Grinder Operator" },
{ "profession": "Grinding and Polishing Worker" },
{ "profession": "Groundskeeper" },
{ "profession": "Groundskeeper Supervisor" },
{ "profession": "Guidance Counselor" },
{ "profession": "Hairdresser" },
{ "profession": "Hand Cutter or Trimmer" },
{ "profession": "Hand Sewer" },
{ "profession": "Hazmat Technician" },
{ "profession": "Head Chef" },
{ "profession": "Health and Safety Engineer" },
{ "profession": "Health Educator" },
{ "profession": "Healthcare Social Worker" },
{ "profession": "Heat Treat Operator" },
{ "profession": "Heavy and Tractor-Trailer Truck Drivers" },
{ "profession": "Heavy Equipment Mechanic" },
{ "profession": "Highway Maintenance Worker" },
{ "profession": "Hoist Operator" },
{ "profession": "Home Health Aide (HHA)" },
{ "profession": "Hospitality Manager - 398" },
{ "profession": "Hospitality Manager - 476" },
{ "profession": "Host" },
{ "profession": "Housekeeping" },
{ "profession": "Human Resources Manager" },
{ "profession": "Human Resources Specialist" },
{ "profession": "Hydrologist" },
{ "profession": "Industrial engineer" },
{ "profession": "Industrial engineering technician" },
{ "profession": "Industrial Machinery Mechanic" },
{ "profession": "Industrial Production Manager" },
{ "profession": "Industrial Truck Operator" },
{ "profession": "Industrial-Organizational Psychologist - 168" },
{ "profession": "Industrial-Organizational Psychologist - 375" },
{ "profession": "Information Security Analyst" },
{ "profession": "Installation and Repair Technician (I & R Technician)" },
{ "profession": "Instructional Coordinator" },
{ "profession": "Insulation Worker" },
{ "profession": "Insulator" },
{ "profession": "Insurance Agent" },
{ "profession": "Insurance Claim Examiner" },
{ "profession": "Insurance Underwriter" },
{ "profession": "Interior Designer" },
{ "profession": "Internist" },
{ "profession": "Interpreter and Translator" },
{ "profession": "Interviewer" },
{ "profession": "Investment Specialist" },
{ "profession": "Janitor" },
{ "profession": "Janitor supervisor" },
{ "profession": "Jeweler" },
{ "profession": "Judge" },
{ "profession": "Kindergarten and Elementary School Special Education Teacher" },
{ "profession": "Kindergarten Teacher" },
{ "profession": "Knitting Machine Operator" },
{ "profession": "Labor Relations Specialist" },
{ "profession": "Landscape Architect" },
{ "profession": "Lathe Operator" },
{ "profession": "Laundry and Dry-Cleaning Worker" },
{ "profession": "Lawyer" },
{ "profession": "Layout Worker" },
{ "profession": "Legislator - 341" },
{ "profession": "Legislator - 390" },
{ "profession": "Legislator - 75" },
{ "profession": "Legislator - 813" },
{ "profession": "Librarian" },
{ "profession": "Library Clerical Assistant" },
{ "profession": "Library technician" },
{ "profession": "Loading Machine Operator" },
{ "profession": "Loan Clerk" },
{ "profession": "Loan Officer" },
{ "profession": "Lobby Attendant" },
{ "profession": "Locker room Attendant" },
{ "profession": "Locomotive Engineer" },
{ "profession": "Locomotive firer" },
{ "profession": "Logging Equipment Operator" },
{ "profession": "Logistician" },
{ "profession": "Logistics Manager" },
{ "profession": "Machine Assembler" },
{ "profession": "Machine Feeders And Offbearer" },
{ "profession": "Machine Operator" },
{ "profession": "Machinist" },
{ "profession": "Maintenance Mechanic" },
{ "profession": "Maintenance Painter" },
{ "profession": "Makeup Artist" },
{ "profession": "Management Consultant" },
{ "profession": "Manicurist" },
{ "profession": "Manufacturing Laborer" },
{ "profession": "Marine Engineer and Naval Architect" },
{ "profession": "Market Research Analyst" },
{ "profession": "Marketing Manager" },
{ "profession": "Marriage and Family Therapist" },
{ "profession": "Material-Moving Machine Supervisor" },
{ "profession": "Materials Engineer" },
{ "profession": "Materials Scientist" },
{ "profession": "Mathematical Technician" },
{ "profession": "Mathematician" },
{ "profession": "Mechanical Drafter" },
{ "profession": "Mechanical Engineer" },
{ "profession": "Mechanical Engineering technician" },
{ "profession": "Medical Appliance Technician" },
{ "profession": "Medical Laboratory Technician (MLT)" },
{ "profession": "Medical Laboratory Technologist (Medical Lab Tech)" },
{ "profession": "Medical Scientist" },
{ "profession": "Mental Health and Substance Abuse Social Worker" },
{ "profession": "Mental Health Counselor" },
{ "profession": "Metal and Plastic Patternmaker" },
{ "profession": "Microbiologist" },
{ "profession": "Middle School Career/Technical Education Teacher" },
{ "profession": "Middle School Special Education Teacher" },
{ "profession": "Middle School Teacher" },
{ "profession": "Mill Operator" },
{ "profession": "Millwright" },
{ "profession": "Mine Shuttle Car Operators" },
{ "profession": "Miner Operator" },
{ "profession": "Mining and geological engineer" },
{ "profession": "Mixing and Blending Machine Setter" },
{ "profession": "Mobile Home Technician" },
{ "profession": "Model" },
{ "profession": "Model Maker, Metal and Plastic" },
{ "profession": "Mortician" },
{ "profession": "Motion Picture Projectionist" },
{ "profession": "Motorboat Operator" },
{ "profession": "Multimedia Artists and Animator" },
{ "profession": "Municipal Fire Fighting and Prevention Supervisor" },
{ "profession": "Music Director and composer" },
{ "profession": "Musician and Singer" },
{ "profession": "Natural Sciences Manager" },
{ "profession": "New Accounts Representative" },
{ "profession": "Nuclear Engineer" },
{ "profession": "Nuclear Power reactor Operator" },
{ "profession": "Nuclear Technician" },
{ "profession": "Nurse Practitioner" },
{ "profession": "Nursing Assistant" },
{ "profession": "Obstetrician and Gynecologist" },
{ "profession": "Occupational Therapist" },
{ "profession": "Oil Field Roustabout" },
{ "profession": "Operating Engineer" },
{ "profession": "Operations Manager" },
{ "profession": "Operations Research Analyst" },
{ "profession": "Ophthalmic Laboratory Technician" },
{ "profession": "Optometrist" },
{ "profession": "Oral and Maxillofacial Surgeon" },
{ "profession": "Order Clerk" },
{ "profession": "Orderly" },
{ "profession": "Orthodontist" },
{ "profession": "Outdoor Emergency Care Technician" },
{ "profession": "Packaging and Filling Machine Operator" },
{ "profession": "Painter Helper" },
{ "profession": "Painting, Coating, and Decorating Workers" },
{ "profession": "Paper Bag Machine Operator" },
{ "profession": "Paperhanger" },
{ "profession": "Paramedic (Emergency Medical Technician, Paramedic)" },
{ "profession": "Parking Enforcement Officer (PEO)" },
{ "profession": "Parking Lot Attendant" },
{ "profession": "Parts Salesperson" },
{ "profession": "Patrol Officer" },
{ "profession": "Payroll Clerk" },
{ "profession": "Pediatrician" },
{ "profession": "Personal care aide" },
{ "profession": "Personal Financial Advisor" },
{ "profession": "Pest Controller" },
{ "profession": "Pesticides Applicator" },
{ "profession": "Petroleum Engineer" },
{ "profession": "Petroleum refinery Operator" },
{ "profession": "Pharmacist" },
{ "profession": "Pharmacy Technician (Pharmacy Tech)" },
{ "profession": "Photographer" },
{ "profession": "Photographic Process Worker" },
{ "profession": "Physical Therapist - 205" },
{ "profession": "Physical Therapist - 258" },
{ "profession": "Physical Therapist Aide (PTA)" },
{ "profession": "Physical Therapy Assistant (PTA) - 42" },
{ "profession": "Physical Therapy Assistant (PTA) - 57" },
{ "profession": "Physician Assistant" },
{ "profession": "Physicist" },
{ "profession": "Pile Driver" },
{ "profession": "Pipelayer" },
{ "profession": "Plasterer" },
{ "profession": "Plating and Coating Machine Setter" },
{ "profession": "Plumber" },
{ "profession": "Plumber's Helper" },
{ "profession": "Political Scientist" },
{ "profession": "Postal Service Clerk" },
{ "profession": "Postmaster" },
{ "profession": "Postsecondary Agricultural Sciences Teacher" },
{ "profession": "Postsecondary Anthropology and Archeology Teacher" },
{ "profession": "Postsecondary Architecture Teacher" },
{ "profession": "Postsecondary Art, Drama, and Music Teacher" },
{ "profession": "Postsecondary Atmospheric, Earth, Marine, and Space Sciences Teacher" },
{ "profession": "Postsecondary Biological Science Teacher" },
{ "profession": "Postsecondary Business Teacher" },
{ "profession": "Postsecondary Chemistry Teacher" },
{ "profession": "Postsecondary Communications Teacher" },
{ "profession": "Postsecondary Computer Science Teacher" },
{ "profession": "Postsecondary Criminal Justice Teacher" },
{ "profession": "Postsecondary Cultural Studies Teacher" },
{ "profession": "Postsecondary Economics Teacher" },
{ "profession": "Postsecondary Education Teacher" },
{ "profession": "Postsecondary Engineering Teacher" },
{ "profession": "Postsecondary English Language Teacher" },
{ "profession": "Postsecondary Environmental Science Teacher" },
{ "profession": "Postsecondary Foreign Language Teacher" },
{ "profession": "Postsecondary Forestry and Conservation Science Teacher" },
{ "profession": "Postsecondary Geography Teacher" },
{ "profession": "Postsecondary Graduate Teaching Assistant" },
{ "profession": "Postsecondary Health Specialties Teacher" },
{ "profession": "Postsecondary History Teacher" },
{ "profession": "Postsecondary Home Economics Teacher" },
{ "profession": "Postsecondary Law Teacher" },
{ "profession": "Postsecondary Library Science Teacher" },
{ "profession": "Postsecondary Mathematical Science Teacher" },
{ "profession": "Postsecondary Nursing Instructor" },
{ "profession": "Postsecondary Philosophy and Religion Teacher" },
{ "profession": "Postsecondary Physics Teacher" },
{ "profession": "Postsecondary Political Science Teacher" },
{ "profession": "Postsecondary Psychology Teacher" },
{ "profession": "Postsecondary Recreation and Fitness Studies Teacher" },
{ "profession": "Postsecondary School Administrator" },
{ "profession": "Postsecondary Social Work Teacher" },
{ "profession": "Postsecondary Sociology Teacher" },
{ "profession": "Postsecondary Vocational Education Teacher" },
{ "profession": "Pourer and Caster, Metal" },
{ "profession": "Power plant operator" },
{ "profession": "Power system dispatcher" },
{ "profession": "Prepress Technician" },
{ "profession": "Preschool Administrator" },
{ "profession": "Preschool Special Education Teacher" },
{ "profession": "Preschool Teacher" },
{ "profession": "Press Machine Operator" },
{ "profession": "Print Binding and Finishing Worker" },
{ "profession": "Printing Press Operator" },
{ "profession": "Private Chef" },
{ "profession": "Private Investigator" },
{ "profession": "Producer and Director" },
{ "profession": "Product Demonstrator" },
{ "profession": "Production Supervisor" },
{ "profession": "Property Manager" },
{ "profession": "Prosthodontist" },
{ "profession": "Psychiatric Technician (PT)" },
{ "profession": "Psychiatrist - 168" },
{ "profession": "Psychiatrist - 375" },
{ "profession": "Psychologist - 168" },
{ "profession": "Psychologist - 375" },
{ "profession": "Public Address System Announcer" },
{ "profession": "Public Relations Manager" },
{ "profession": "Public Relations Specialist" },
{ "profession": "Public Transit Bus Driver" },
{ "profession": "Pump Operators, Except Wellhead Pumpers" },
{ "profession": "Purchasing Agent" },
{ "profession": "Purchasing Manager" },
{ "profession": "Quality Control Inspector" },
{ "profession": "Race And Sports Book Writer" },
{ "profession": "Radiation Therapist" },
{ "profession": "Radio and Television Announcer" },
{ "profession": "Radio Operator" },
{ "profession": "Rail Yard Engineers" },
{ "profession": "Railway Switch Operator" },
{ "profession": "Rapid Transit Operator" },
{ "profession": "Real Estate Agent" },
{ "profession": "Real Estate Appraiser" },
{ "profession": "Real Estate Broker" },
{ "profession": "Receptionist" },
{ "profession": "Recreation Attendant" },
{ "profession": "Recreation Specialist" },
{ "profession": "Recreational Therapist" },
{ "profession": "Recreational Vehicle Service Technician" },
{ "profession": "Recyclable Materials Collector" },
{ "profession": "Refrigerating Machine Operator" },
{ "profession": "Rehabilitation Counselor" },
{ "profession": "Reinforced Ironworker" },
{ "profession": "Religious Education Director" },
{ "profession": "Reporter and Correspondent" },
{ "profession": "Reservations Agent" },
{ "profession": "Resident Advisor" },
{ "profession": "Respiratory Therapist" },
{ "profession": "Respiratory Therapy Technician" },
{ "profession": "Restaurant Cook" },
{ "profession": "Retail Salesperson" },
{ "profession": "Rigger" },
{ "profession": "Rock Splitter" },
{ "profession": "Rolling Machine Operator" },
{ "profession": "Roof Bolter" },
{ "profession": "Roofer" },
{ "profession": "Roofer Helper" },
{ "profession": "Sales Engineer" },
{ "profession": "Sales Manager" },
{ "profession": "Sales Representative" },
{ "profession": "Saw Operator" },
{ "profession": "School Bus Driver" },
{ "profession": "Seaman" },
{ "profession": "Secondary School Career/Technical Education Teacher" },
{ "profession": "Secondary School Special Education Teacher" },
{ "profession": "Secondary School Teacher" },
{ "profession": "Security guard" },
{ "profession": "Security Installer" },
{ "profession": "Segmental Paver" },
{ "profession": "Self-Enrichment Education Teacher" },
{ "profession": "Semiconductor Processor" },
{ "profession": "Septic Service Technician" },
{ "profession": "Service Operator" },
{ "profession": "Set and Exhibit Designer" },
{ "profession": "Sewing Machine Operator" },
{ "profession": "Shampooer" },
{ "profession": "Sheet Metal Worker" },
{ "profession": "Ship Engineer" },
{ "profession": "Shoe and Leather Repair" },
{ "profession": "Shoe Machine Operators and Tender" },
{ "profession": "Skin Care Specialist" },
{ "profession": "Slaughterer" },
{ "profession": "Slot Supervisor" },
{ "profession": "Social and Human Service Assistant" },
{ "profession": "Social Science Research Assistant" },
{ "profession": "Sociologist" },
{ "profession": "Soil and Plant Scientist" },
{ "profession": "Solar Photovoltaic Installer" },
{ "profession": "Sound Engineering Technician" },
{ "profession": "Sports Official" },
{ "profession": "Spraying Machine Operator" },
{ "profession": "Statistician - 135" },
{ "profession": "Stockroom Clerk" },
{ "profession": "Stone Mason" },
{ "profession": "Street Vendor" },
{ "profession": "Structural Metal Fabricators and Fitter" },
{ "profession": "Structural Steel Erector" },
{ "profession": "Substance Abuse and Behavioral Disorder Counselor" },
{ "profession": "Substitute Teacher" },
{ "profession": "Supervisor of Farming, Fishing, and Forestry Workers" },
{ "profession": "Supervisor of personal service workers" },
{ "profession": "Surgeon" },
{ "profession": "Surgical Technologist (Surgical Tech)" },
{ "profession": "Survey Researcher" },
{ "profession": "Surveying and mapping technician" },
{ "profession": "Surveyor" },
{ "profession": "Switchboard Operator" },
{ "profession": "Synthetic Filament Extruder" },
{ "profession": "System Software Developer" },
{ "profession": "Systems Administrator" },
{ "profession": "Table Games Supervisor" },
{ "profession": "Tailor" },
{ "profession": "Talent Manager - 138" },
{ "profession": "Talent Manager - 162" },
{ "profession": "Tank Car, Truck, and Ship Loader" },
{ "profession": "Taper" },
{ "profession": "Tax Examiner" },
{ "profession": "Tax Specialist" },
{ "profession": "Taxi Drivers and Chauffeurs" },
{ "profession": "Teacher Assistant" },
{ "profession": "Team Assembler" },
{ "profession": "Technical Sales Representative" },
{ "profession": "Technical Writer" },
{ "profession": "Telecommunications Technician" },
{ "profession": "Telemarketer" },
{ "profession": "Telephone Operator" },
{ "profession": "Teller" },
{ "profession": "Terrazzo Worker" },
{ "profession": "Tile and Marble Setter" },
{ "profession": "Tire Builder" },
{ "profession": "Tire Repairer" },
{ "profession": "Tool and Die Maker" },
{ "profession": "Tool Grinder" },
{ "profession": "Tour Guide" },
{ "profession": "Track Equipment Operator (TEO)" },
{ "profession": "Traffic Technician" },
{ "profession": "Train Control Technician" },
{ "profession": "Training and Development Manager" },
{ "profession": "Training and Development Specialist" },
{ "profession": "Transit Police Officer" },
{ "profession": "Transportation Attendant" },
{ "profession": "Transportation Inspector" },
{ "profession": "Transportation Security Officer" },
{ "profession": "Travel Agent" },
{ "profession": "Travel Guide" },
{ "profession": "Tree Faller" },
{ "profession": "Tree trimmer" },
{ "profession": "Upholsterer" },
{ "profession": "Urban and Regional Planner" },
{ "profession": "Utility Bagger" },
{ "profession": "Valve Technician" },
{ "profession": "Veterinarian" },
{ "profession": "Veterinarian Assistant" },
{ "profession": "Visual Merchandiser" },
{ "profession": "Waiter" },
{ "profession": "Waiter Assistant" },
{ "profession": "Waste Treatment Operator" },
{ "profession": "Web Developer - 30" },
{ "profession": "Web Developer - 89" },
{ "profession": "Welder" },
{ "profession": "Welders, Cutters, Solderers, and Brazers" },
{ "profession": "Wellhead Pumper" },
{ "profession": "Wholesale and Retail Buyer" },
{ "profession": "Wildfire Prevention Specialist" },
{ "profession": "Wildlife Biologist" },
{ "profession": "Wind Turbine Service Technician" },
{ "profession": "Wood Model Maker" },
{ "profession": "Wood Pattern Maker" },
{ "profession": "Woodworking Machine Setter/Operator" },
{ "profession": "Writers and Author" }
    ];